insert into auth.users (
		instance_id,
		id,
		aud,
		role,
		email,
		encrypted_password,
		email_confirmed_at,
		recovery_sent_at,
		last_sign_in_at,
		raw_app_meta_data,
		raw_user_meta_data,
		created_at,
		updated_at,
		confirmation_token,
		email_change,
		email_change_token_new,
		recovery_token
	)
values (
		'00000000-0000-0000-0000-000000000000',
		uuid_generate_v4 (),
		'authenticated',
		'authenticated',
		'joao.nogueira@imoflor.pt',
		crypt ('Password123', gen_salt ('bf')),
		current_timestamp,
		current_timestamp,
		current_timestamp,
		'{"provider":"email","providers":["email"]}',
		'{"display_name": "João Nogueira"}',
		current_timestamp,
		current_timestamp,
		'',
		'',
		'',
		''
	),
	(
		'00000000-0000-0000-0000-000000000000',
		uuid_generate_v4 (),
		'authenticated',
		'authenticated',
		'goncalo.nogueira@imoflor.pt',
		crypt ('Password123', gen_salt ('bf')),
		current_timestamp,
		current_timestamp,
		current_timestamp,
		'{"provider":"email","providers":["email"]}',
		'{"display_name": "Gonçalo Nogueira"}',
		current_timestamp,
		current_timestamp,
		'',
		'',
		'',
		''
	),
	(
		'00000000-0000-0000-0000-000000000000',
		uuid_generate_v4 (),
		'authenticated',
		'authenticated',
		'paula.raimundo@imoflor.pt',
		crypt ('Password123', gen_salt ('bf')),
		current_timestamp,
		current_timestamp,
		current_timestamp,
		'{"provider":"email","providers":["email"]}',
		'{"display_name": "Paula Raimundo"}',
		current_timestamp,
		current_timestamp,
		'',
		'',
		'',
		''
	),
	(
		'00000000-0000-0000-0000-000000000000',
		uuid_generate_v4 (),
		'authenticated',
		'authenticated',
		'patricia.pereira@imoflor.pt',
		crypt ('Password123', gen_salt ('bf')),
		current_timestamp,
		current_timestamp,
		current_timestamp,
		'{"provider":"email","providers":["email"]}',
		'{"display_name": "Patrícia Pereira"}',
		current_timestamp,
		current_timestamp,
		'',
		'',
		'',
		''
	);
insert into auth.identities (
		id,
		user_id,
		provider_id,
		identity_data,
		provider,
		last_sign_in_at,
		created_at,
		updated_at
	) (
		select uuid_generate_v4 (),
			id,
			id,
			format('{"sub":"%s","email":"%s"}', id::text, email)::jsonb,
			'email',
			current_timestamp,
			current_timestamp,
			current_timestamp
		from auth.users
	);