-- =============================================
-- SCHEMA: Addresses
-- DESCRIPTION: ... teste
-- =============================================
-- Tables
CREATE TABLE public.addresses(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  inserted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  country text NOT NULL,
  region text NOT NULL,
  address text NOT NULL,
  postal_code text NOT NULL,
  city text NOT NULL,
  CONSTRAINT pk_addresses PRIMARY KEY (id)
);

