-- =============================================
-- SCHEMA: Addresses
-- DESCRIPTION: ...
-- =============================================
-- Tables
CREATE TABLE public.addresses(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  inserted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  country text,
  region text,
  address text,
  postal_code text,
  city text,
  CONSTRAINT pk_addresses PRIMARY KEY (id)
);

