-- =============================================================================
-- Contracts
-- Renting and lending contracts, payments, due notes, and related views.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Enums
-- -----------------------------------------------------------------------------

CREATE TYPE public.contract_type AS ENUM(
  'renting',
  'lending'
);

-- -----------------------------------------------------------------------------
-- Tables
-- -----------------------------------------------------------------------------

CREATE TABLE public.contracts(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by uuid REFERENCES public.users(id),
  updated_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by uuid REFERENCES public.users(id),
  type public.contract_type NOT NULL,
  start_date date NOT NULL,
  end_date date,
  property_id bigint NOT NULL,
  is_active boolean NOT NULL DEFAULT TRUE,
  CONSTRAINT pk_contracts PRIMARY KEY (id),
  CONSTRAINT fk_contracts_property_id FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE CASCADE,
  CONSTRAINT uq_contracts_id_type UNIQUE (id, type),
  CONSTRAINT ck_contracts_end_date CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE UNIQUE INDEX idx_contracts_property_id_active
  ON public.contracts(property_id)
  WHERE is_active;

CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.contracts
  FOR EACH ROW
  EXECUTE PROCEDURE moddatetime(updated_at);

CREATE TRIGGER handle_audit_columns
  BEFORE INSERT OR UPDATE ON public.contracts
  FOR EACH ROW
  EXECUTE PROCEDURE handle_audit_columns();

CREATE TABLE public.contracts_tenants(
  contract_id bigint NOT NULL,
  tenant_id bigint NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by uuid REFERENCES public.users(id),
  updated_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by uuid REFERENCES public.users(id),
  CONSTRAINT pk_contracts_tenants PRIMARY KEY (contract_id, tenant_id),
  CONSTRAINT fk_contracts_tenants_contract_id FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON DELETE CASCADE,
  CONSTRAINT fk_contracts_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE
);

CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.contracts_tenants
  FOR EACH ROW
  EXECUTE PROCEDURE moddatetime(updated_at);

CREATE TRIGGER handle_audit_columns
  BEFORE INSERT OR UPDATE ON public.contracts_tenants
  FOR EACH ROW
  EXECUTE PROCEDURE handle_audit_columns();

CREATE TABLE public.due_notes(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by uuid REFERENCES public.users(id),
  updated_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by uuid REFERENCES public.users(id),
  contract_id bigint NOT NULL,
  due_date date NOT NULL,
  value numeric(15, 2) NOT NULL,
  CONSTRAINT pk_due_notes PRIMARY KEY (id),
  CONSTRAINT fk_due_notes_contract_id FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON DELETE CASCADE,
  CONSTRAINT uq_due_notes_contract_due_date UNIQUE (contract_id, due_date)
);

CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.due_notes
  FOR EACH ROW
  EXECUTE PROCEDURE moddatetime(updated_at);

CREATE TRIGGER handle_audit_columns
  BEFORE INSERT OR UPDATE ON public.due_notes
  FOR EACH ROW
  EXECUTE PROCEDURE handle_audit_columns();

CREATE TABLE public.renting_contracts(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by uuid REFERENCES public.users(id),
  updated_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by uuid REFERENCES public.users(id),
  contract_type public.contract_type NOT NULL GENERATED ALWAYS AS ('renting'::public.contract_type) STORED,
  CONSTRAINT pk_renting_contracts PRIMARY KEY (id),
  CONSTRAINT fk_renting_contracts_id_contract_type FOREIGN KEY (id, contract_type) REFERENCES public.contracts(id, type) ON DELETE CASCADE
);

CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.renting_contracts
  FOR EACH ROW
  EXECUTE PROCEDURE moddatetime(updated_at);

CREATE TRIGGER handle_audit_columns
  BEFORE INSERT OR UPDATE ON public.renting_contracts
  FOR EACH ROW
  EXECUTE PROCEDURE handle_audit_columns();

CREATE TABLE public.rent_updates(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  created_by uuid REFERENCES public.users(id),
  updated_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by uuid REFERENCES public.users(id),
  update_date date NOT NULL,
  rent numeric(15, 2) NOT NULL,
  contract_id bigint NOT NULL,
  CONSTRAINT pk_rent_updates PRIMARY KEY (id),
  CONSTRAINT fk_rent_updates_contract_id FOREIGN KEY (contract_id) REFERENCES public.renting_contracts(id) ON DELETE CASCADE
);

CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.rent_updates
  FOR EACH ROW
  EXECUTE PROCEDURE moddatetime(updated_at);

CREATE TRIGGER handle_audit_columns
  BEFORE INSERT OR UPDATE ON public.rent_updates
  FOR EACH ROW
  EXECUTE PROCEDURE handle_audit_columns();

CREATE TABLE public.rent_payments(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by uuid REFERENCES public.users(id),
  updated_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by uuid REFERENCES public.users(id),
  contract_id bigint NOT NULL,
  movement_id bigint NOT NULL,
  CONSTRAINT pk_rent_payments PRIMARY KEY (id),
  CONSTRAINT fk_rent_payments_contract_id FOREIGN KEY (contract_id) REFERENCES public.renting_contracts(id) ON DELETE CASCADE,
  CONSTRAINT fk_rent_payments_movement_id FOREIGN KEY (movement_id) REFERENCES public.movements(id)
);

CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.rent_payments
  FOR EACH ROW
  EXECUTE PROCEDURE moddatetime(updated_at);

CREATE TRIGGER handle_audit_columns
  BEFORE INSERT OR UPDATE ON public.rent_payments
  FOR EACH ROW
  EXECUTE PROCEDURE handle_audit_columns();

CREATE TABLE public.lending_contracts(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by uuid REFERENCES public.users(id),
  updated_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by uuid REFERENCES public.users(id),
  contract_type public.contract_type NOT NULL GENERATED ALWAYS AS ('lending'::public.contract_type) STORED,
  sale_value numeric(15, 2) NOT NULL,
  down_payment numeric(15, 2) NOT NULL,
  yearly_raise numeric(15, 2) NOT NULL,
  CONSTRAINT pk_lending_contracts PRIMARY KEY (id),
  CONSTRAINT fk_lending_contracts_id_contract_type FOREIGN KEY (id, contract_type) REFERENCES public.contracts(id, type) ON DELETE CASCADE,
  CONSTRAINT ck_lending_contracts_values CHECK (down_payment >= 0 AND sale_value >= down_payment)
);

CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.lending_contracts
  FOR EACH ROW
  EXECUTE PROCEDURE moddatetime(updated_at);

CREATE TRIGGER handle_audit_columns
  BEFORE INSERT OR UPDATE ON public.lending_contracts
  FOR EACH ROW
  EXECUTE PROCEDURE handle_audit_columns();

CREATE TABLE public.installment_updates(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  created_by uuid REFERENCES public.users(id),
  updated_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by uuid REFERENCES public.users(id),
  update_date date NOT NULL,
  installment numeric(15, 2) NOT NULL,
  interest numeric(15, 2) NOT NULL,
  contract_id bigint NOT NULL,
  CONSTRAINT pk_installment_updates PRIMARY KEY (id),
  CONSTRAINT fk_installment_updates_contract_id FOREIGN KEY (contract_id) REFERENCES public.lending_contracts(id) ON DELETE CASCADE
);

CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.installment_updates
  FOR EACH ROW
  EXECUTE PROCEDURE moddatetime(updated_at);

CREATE TRIGGER handle_audit_columns
  BEFORE INSERT OR UPDATE ON public.installment_updates
  FOR EACH ROW
  EXECUTE PROCEDURE handle_audit_columns();

CREATE TABLE public.installment_payments(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by uuid REFERENCES public.users(id),
  updated_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by uuid REFERENCES public.users(id),
  contract_id bigint NOT NULL,
  interest_movement_id bigint NOT NULL,
  amortization_movement_id bigint,
  extra_debt numeric(15, 2),
  CONSTRAINT pk_installment_payments PRIMARY KEY (id),
  CONSTRAINT fk_installment_payments_contract_id FOREIGN KEY (contract_id) REFERENCES public.lending_contracts(id) ON DELETE CASCADE,
  CONSTRAINT fk_installment_payments_interest_movement_id FOREIGN KEY (interest_movement_id) REFERENCES public.movements(id),
  CONSTRAINT fk_installment_payments_amortization_movement_id FOREIGN KEY (amortization_movement_id) REFERENCES public.movements(id)
);

CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.installment_payments
  FOR EACH ROW
  EXECUTE PROCEDURE moddatetime(updated_at);

CREATE TRIGGER handle_audit_columns
  BEFORE INSERT OR UPDATE ON public.installment_payments
  FOR EACH ROW
  EXECUTE PROCEDURE handle_audit_columns();

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

CREATE INDEX idx_contracts_property_id ON public.contracts(property_id);

CREATE INDEX idx_contracts_tenants_tenant_id ON public.contracts_tenants(tenant_id);

CREATE INDEX idx_rent_updates_contract_update_date ON public.rent_updates(contract_id, update_date DESC);

CREATE INDEX idx_rent_updates_contract_created_at ON public.rent_updates(contract_id, created_at DESC);

CREATE INDEX idx_rent_payments_contract_id ON public.rent_payments(contract_id);

CREATE INDEX idx_rent_payments_movement_id ON public.rent_payments(movement_id);

CREATE INDEX idx_installment_updates_contract_update_date ON public.installment_updates(contract_id, update_date DESC);

CREATE INDEX idx_installment_updates_contract_created_at ON public.installment_updates(contract_id, created_at DESC);

CREATE INDEX idx_installment_payments_contract_id ON public.installment_payments(contract_id);

CREATE INDEX idx_installment_payments_interest_movement_id ON public.installment_payments(interest_movement_id);

CREATE INDEX idx_installment_payments_amortization_movement_id ON public.installment_payments(amortization_movement_id);

-- -----------------------------------------------------------------------------
-- Views
-- -----------------------------------------------------------------------------

CREATE VIEW public.rent_payments_view
  WITH (security_invoker = TRUE) AS
SELECT
  rp.contract_id,
  rp.id,
  m.value,
  m.occurred_at AS paid_at,
  m.description
FROM
  public.rent_payments rp
  JOIN public.movements m ON rp.movement_id = m.id;

CREATE VIEW public.installment_payments_view
  WITH (security_invoker = TRUE) AS
SELECT
  ip.contract_id,
  ip.id,
  i.occurred_at AS paid_at,
  i.value AS interest,
  COALESCE(a.value, 0::numeric) AS amortization,
  ip.extra_debt,
  i.description
FROM
  public.installment_payments ip
  LEFT JOIN public.movements a ON ip.amortization_movement_id = a.id
  LEFT JOIN public.movements i ON ip.interest_movement_id = i.id;

CREATE VIEW public.contracts_accounts_view
  WITH (security_invoker = TRUE) AS
SELECT
  dn.contract_id,
  dn.id,
  'due_note' AS type,
  (dn.due_date::timestamp AT TIME ZONE 'UTC') AS date,
  -1 * dn.value AS value
FROM
  public.due_notes dn
UNION
SELECT
  rp.contract_id,
  rp.id,
  'payment' AS type,
  rp.paid_at AS date,
  rp.value AS value
FROM
  public.rent_payments_view rp
UNION
SELECT
  ip.contract_id,
  ip.id,
  'payment' AS type,
  ip.paid_at AS date,
  ip.interest + ip.amortization AS value
FROM
  public.installment_payments_view ip;

CREATE VIEW public.contracts_balances_view
  WITH (security_invoker = TRUE) AS
SELECT
  c.id AS contract_id,
  COALESCE(sum(ca.value), 0) AS balance
FROM
  public.contracts c
  LEFT JOIN public.contracts_accounts_view ca ON c.id = ca.contract_id
GROUP BY
  c.id;

CREATE VIEW public.lending_contracts_debts_view
  WITH (security_invoker = TRUE) AS
SELECT
  lc.id,
  lc.sale_value - lc.down_payment - COALESCE(sum(ip.amortization), 0) AS debt,
  COALESCE((
    SELECT
      ip.extra_debt
    FROM public.installment_payments_view ip
    WHERE
      ip.contract_id = lc.id ORDER BY ip.paid_at DESC LIMIT 1), 0) AS extra_debt,
  max(ip.paid_at) AS last_paid_at
FROM
  public.lending_contracts lc
  LEFT JOIN public.installment_payments_view ip ON lc.id = ip.contract_id
GROUP BY
  lc.id;

CREATE VIEW public.lending_contracts_view
  WITH (security_invoker = TRUE) AS
SELECT
  lc.*,
  lcd.debt,
  lcd.extra_debt,
  lcd.last_paid_at,
  COALESCE(active_updates.installment, 0) AS installment,
  COALESCE(active_updates.interest, 0) AS interest,
  CASE WHEN last_updates.update_date IS NULL THEN
    NULL::json
  ELSE
    JSON_BUILD_OBJECT('update_date', last_updates.update_date, 'installment', COALESCE(last_updates.installment, 0), 'interest', COALESCE(last_updates.interest, 0))
  END AS next_update
FROM
  public.lending_contracts lc
  LEFT JOIN public.lending_contracts_debts_view lcd ON lc.id = lcd.id
  LEFT JOIN ( SELECT DISTINCT ON (iu.contract_id)
      iu.contract_id,
      iu.installment,
      iu.interest,
      iu.update_date
    FROM
      public.installment_updates iu
    ORDER BY
      iu.contract_id,
      iu.created_at DESC) AS last_updates ON lc.id = last_updates.contract_id
  LEFT JOIN ( SELECT DISTINCT ON (iu.contract_id)
      iu.contract_id,
      iu.installment,
      iu.interest,
      iu.update_date
    FROM
      public.installment_updates iu
    WHERE
      iu.update_date <= CURRENT_DATE
    ORDER BY
      iu.contract_id,
      iu.update_date DESC) AS active_updates ON lc.id = active_updates.contract_id;

CREATE VIEW public.renting_contracts_view
  WITH (security_invoker = TRUE) AS
SELECT
  rc.*,
  COALESCE(active_updates.rent, 0) AS rent,
  CASE WHEN next_updates.update_date IS NULL THEN
    NULL::json
  ELSE
    JSON_BUILD_OBJECT('update_date', next_updates.update_date, 'rent', next_updates.rent)
  END AS next_update
FROM
  public.renting_contracts rc
  LEFT JOIN ( SELECT DISTINCT ON (ru.contract_id)
      ru.contract_id,
      ru.rent,
      ru.update_date
    FROM
      public.rent_updates ru
    WHERE
      ru.update_date <= CURRENT_DATE
    ORDER BY
      ru.contract_id,
      ru.update_date DESC) AS active_updates ON rc.id = active_updates.contract_id
  LEFT JOIN ( SELECT DISTINCT ON (ru.contract_id)
      ru.contract_id,
      ru.rent,
      ru.update_date
    FROM
      public.rent_updates ru
    WHERE
      ru.update_date > CURRENT_DATE
    ORDER BY
      ru.contract_id,
      ru.created_at DESC) AS next_updates ON rc.id = next_updates.contract_id;

CREATE VIEW public.contracts_view
  WITH (security_invoker = TRUE) AS
SELECT
  c.*,
  cb.balance,
  CASE WHEN c.type = 'lending'::public.contract_type THEN
  (
    SELECT
      TO_JSON(lcv.*)
    FROM
      public.lending_contracts_view lcv
    WHERE
      lcv.id = c.id)
  WHEN c.type = 'renting'::public.contract_type THEN
  (
    SELECT
      TO_JSON(rcv.*)
    FROM
      public.renting_contracts_view rcv
    WHERE
      rcv.id = c.id)
  ELSE
    NULL::json
  END AS data
FROM
  public.contracts c
  LEFT JOIN public.contracts_balances_view cb ON c.id = cb.contract_id;

-- -----------------------------------------------------------------------------
-- Functions
-- -----------------------------------------------------------------------------

CREATE FUNCTION public.insert_contract()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path = ''
  AS $$
DECLARE
  contract_id bigint;
  inserted_contract public.contracts_view % ROWTYPE;
BEGIN
  INSERT INTO public.contracts(type, start_date, end_date, property_id)
    VALUES (NEW.type, NEW.start_date, NEW.end_date, NEW.property_id)
  RETURNING
    id INTO contract_id;
  IF NEW.type = 'renting' THEN
    INSERT INTO public.renting_contracts(id)
      VALUES (contract_id);
    INSERT INTO public.rent_updates(contract_id, update_date, rent)
      VALUES (contract_id, NEW.start_date,(NEW.data ->> 'rent')::numeric);
  ELSIF NEW.type = 'lending' THEN
    INSERT INTO public.lending_contracts(id, sale_value, down_payment, yearly_raise)
      VALUES (contract_id,(NEW.data ->> 'sale_value')::numeric,(NEW.data ->> 'down_payment')::numeric,(NEW.data ->> 'yearly_raise')::numeric);
    INSERT INTO public.installment_updates(contract_id, update_date, installment, interest)
      VALUES (contract_id, NEW.start_date,(NEW.data ->> 'installment')::numeric,(NEW.data ->> 'interest')::numeric);
  END IF;
  SELECT
    * INTO inserted_contract
  FROM
    public.contracts_view
  WHERE
    id = contract_id;
  RETURN inserted_contract;
END;
$$;

CREATE FUNCTION public.update_contract()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path = ''
  AS $$
DECLARE
  contract_id bigint;
  updated_contract public.contracts_view % ROWTYPE;
BEGIN
  contract_id := NEW.id;
  UPDATE
    public.contracts
  SET
    start_date = NEW.start_date,
    end_date = NEW.end_date,
    property_id = NEW.property_id
  WHERE
    id = contract_id;
  IF NEW.type = 'renting' THEN
    INSERT INTO public.rent_updates(contract_id, update_date, rent)
      VALUES (contract_id, NEW.start_date,(NEW.data ->> 'rent')::numeric);
  ELSIF NEW.type = 'lending' THEN
    UPDATE
      public.lending_contracts
    SET
      sale_value =(NEW.data ->> 'sale_value')::numeric,
      down_payment =(NEW.data ->> 'down_payment')::numeric,
      yearly_raise =(NEW.data ->> 'yearly_raise')::numeric
    WHERE
      id = contract_id;
    INSERT INTO public.installment_updates(contract_id, update_date, installment, interest)
      VALUES (contract_id, NEW.start_date,(NEW.data ->> 'installment')::numeric,(NEW.data ->> 'interest')::numeric);
  END IF;
  SELECT
    * INTO updated_contract
  FROM
    public.contracts_view
  WHERE
    id = contract_id;
  RETURN updated_contract;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_contract_tenants(p_contract_id bigint, p_tenants bigint[])
  RETURNS void
  LANGUAGE plpgsql
  SET search_path = ''
  AS $$
BEGIN
  DELETE FROM public.contracts_tenants
  WHERE contract_id = p_contract_id;
  INSERT INTO public.contracts_tenants(contract_id, tenant_id)
  SELECT
    p_contract_id,
    unnest(p_tenants);
END;
$$;

CREATE FUNCTION public.insert_rent_payment()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path = ''
  AS $$
DECLARE
  movement_id bigint;
BEGIN
  INSERT INTO public.movements(type, value, occurred_at, description)
    VALUES ('rent'::public.movement_type, NEW.value, NEW.paid_at, NEW.description)
  RETURNING
    id INTO movement_id;
  INSERT INTO public.rent_payments(contract_id, movement_id)
    VALUES (NEW.contract_id, movement_id);
  RETURN NEW;
END;
$$;

CREATE FUNCTION public.remove_rent_payment()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path = ''
  AS $$
BEGIN
  DELETE FROM public.rent_payments
  WHERE id = OLD.id;
  DELETE FROM public.movements
  WHERE id = OLD.movement_id;
  RETURN OLD;
END;
$$;

CREATE FUNCTION public.insert_installment_payment()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path = ''
  AS $$
DECLARE
  interest_movement_id bigint;
  amortization_movement_id bigint;
BEGIN
  INSERT INTO public.movements(type, value, occurred_at, description)
    VALUES ('installment_interest'::public.movement_type, NEW.interest, NEW.paid_at, NEW.description)
  RETURNING
    id INTO interest_movement_id;
  IF NEW.amortization > 0 THEN
    INSERT INTO public.movements(type, value, occurred_at, description)
      VALUES ('installment_amortization'::public.movement_type, NEW.amortization, NEW.paid_at, NEW.description)
    RETURNING
      id INTO amortization_movement_id;
  END IF;
  INSERT INTO public.installment_payments(contract_id, interest_movement_id, amortization_movement_id, extra_debt)
    VALUES (NEW.contract_id, interest_movement_id, amortization_movement_id, NEW.extra_debt);
  RETURN NEW;
END;
$$;

CREATE FUNCTION public.remove_installment_payment()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path = ''
  AS $$
BEGIN
  DELETE FROM public.installment_payments
  WHERE id = OLD.id;
  DELETE FROM public.movements
  WHERE id = OLD.interest_movement_id;
  DELETE FROM public.movements
  WHERE id = OLD.amortization_movement_id;
  RETURN OLD;
END;
$$;

-- -----------------------------------------------------------------------------
-- Triggers
-- -----------------------------------------------------------------------------

CREATE TRIGGER insert_contract
  INSTEAD OF INSERT ON public.contracts_view
  FOR EACH ROW
  EXECUTE PROCEDURE public.insert_contract();

CREATE TRIGGER update_contract
  INSTEAD OF UPDATE ON public.contracts_view
  FOR EACH ROW
  EXECUTE PROCEDURE public.update_contract();

CREATE TRIGGER insert_rent_payment
  INSTEAD OF INSERT ON public.rent_payments_view
  FOR EACH ROW
  EXECUTE PROCEDURE public.insert_rent_payment();

CREATE TRIGGER remove_rent_payment
  INSTEAD OF DELETE ON public.rent_payments_view
  FOR EACH ROW
  EXECUTE PROCEDURE public.remove_rent_payment();

CREATE TRIGGER insert_installment_payment
  INSTEAD OF INSERT ON public.installment_payments_view
  FOR EACH ROW
  EXECUTE PROCEDURE public.insert_installment_payment();

CREATE TRIGGER remove_installment_payment
  INSTEAD OF DELETE ON public.installment_payments_view
  FOR EACH ROW
  EXECUTE PROCEDURE public.remove_installment_payment();

-- -----------------------------------------------------------------------------
-- Cron
-- -----------------------------------------------------------------------------

SELECT
  cron.schedule('create-due-notes', '0 5 1 * *', $$ INSERT INTO public.due_notes(contract_id, due_date, value)
    SELECT
      c.id,
      date_trunc('month', CURRENT_DATE)::date,
      CASE WHEN c.type = 'renting'::public.contract_type THEN
        COALESCE(rcv.rent, 0)
      WHEN c.type = 'lending'::public.contract_type THEN
        COALESCE(lcv.installment, 0)
      ELSE
        0
      END
    FROM
      public.contracts c
      LEFT JOIN public.renting_contracts_view rcv ON c.type = 'renting'::public.contract_type
        AND rcv.id = c.id
      LEFT JOIN public.lending_contracts_view lcv ON c.type = 'lending'::public.contract_type
        AND lcv.id = c.id
    WHERE
      c.is_active ON CONFLICT ON CONSTRAINT uq_due_notes_contract_due_date DO NOTHING $$);

-- -----------------------------------------------------------------------------
-- Grants
-- -----------------------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON public.contracts TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.contracts_tenants TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.due_notes TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.renting_contracts TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.rent_updates TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.rent_payments TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lending_contracts TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.installment_updates TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.installment_payments TO authenticated, service_role;

GRANT SELECT ON public.contracts_accounts_view TO authenticated, service_role;
GRANT SELECT ON public.contracts_balances_view TO authenticated, service_role;
GRANT SELECT ON public.lending_contracts_debts_view TO authenticated, service_role;
GRANT SELECT ON public.lending_contracts_view TO authenticated, service_role;
GRANT SELECT ON public.renting_contracts_view TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.contracts_view TO authenticated, service_role;
GRANT SELECT, INSERT, DELETE ON public.rent_payments_view TO authenticated, service_role;
GRANT SELECT, INSERT, DELETE ON public.installment_payments_view TO authenticated, service_role;

GRANT EXECUTE ON FUNCTION public.update_contract_tenants(bigint, bigint[]) TO authenticated, service_role;

-- -----------------------------------------------------------------------------
-- Row Level Security
-- -----------------------------------------------------------------------------

ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_crud" ON public.contracts
  FOR ALL TO authenticated
  USING (TRUE)
  WITH CHECK (TRUE);

ALTER TABLE public.contracts_tenants ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_crud" ON public.contracts_tenants
  FOR ALL TO authenticated
  USING (TRUE)
  WITH CHECK (TRUE);

ALTER TABLE public.due_notes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_crud" ON public.due_notes
  FOR ALL TO authenticated
  USING (TRUE)
  WITH CHECK (TRUE);

ALTER TABLE public.renting_contracts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_crud" ON public.renting_contracts
  FOR ALL TO authenticated
  USING (TRUE)
  WITH CHECK (TRUE);

ALTER TABLE public.rent_updates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_crud" ON public.rent_updates
  FOR ALL TO authenticated
  USING (TRUE)
  WITH CHECK (TRUE);

ALTER TABLE public.rent_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_crud" ON public.rent_payments
  FOR ALL TO authenticated
  USING (TRUE)
  WITH CHECK (TRUE);

ALTER TABLE public.lending_contracts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_crud" ON public.lending_contracts
  FOR ALL TO authenticated
  USING (TRUE)
  WITH CHECK (TRUE);

ALTER TABLE public.installment_updates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_crud" ON public.installment_updates
  FOR ALL TO authenticated
  USING (TRUE)
  WITH CHECK (TRUE);

ALTER TABLE public.installment_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_crud" ON public.installment_payments
  FOR ALL TO authenticated
  USING (TRUE)
  WITH CHECK (TRUE);

