-- =============================================================================
-- Employees
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Enums
-- -----------------------------------------------------------------------------

CREATE TYPE public.salary_type AS ENUM(
  'hourly',
  'monthly'
);

-- -----------------------------------------------------------------------------
-- Tables
-- -----------------------------------------------------------------------------

CREATE TABLE public.employees(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by uuid REFERENCES public.users(id),
  updated_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by uuid REFERENCES public.users(id),
  name text NOT NULL,
  gender public.gender NOT NULL,
  marital_status public.marital_status NOT NULL,
  nationality text NOT NULL,
  birth_date date,
  id_type text NOT NULL,
  id_expiration_date date,
  id_number text NOT NULL,
  tax_id_number text NOT NULL,
  ss_number text NOT NULL,
  address_id bigint NOT NULL,
  email text,
  mobile text,
  phone text,
  position text NOT NULL,
  salary_type public.salary_type NOT NULL,
  salary numeric(15, 2) NOT NULL,
  CONSTRAINT pk_employees PRIMARY KEY (id),
  CONSTRAINT fk_employees_address_id FOREIGN KEY (address_id) REFERENCES public.addresses(id),
  CONSTRAINT uq_employees_tax_id_number UNIQUE (tax_id_number)
);

CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.employees
  FOR EACH ROW
  EXECUTE PROCEDURE moddatetime(updated_at);

CREATE TRIGGER handle_audit_columns
  BEFORE INSERT OR UPDATE ON public.employees
  FOR EACH ROW
  EXECUTE PROCEDURE handle_audit_columns();

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

CREATE INDEX idx_employees_address_id ON public.employees(address_id);

-- -----------------------------------------------------------------------------
-- Grants
-- -----------------------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON public.employees TO authenticated, service_role;

-- -----------------------------------------------------------------------------
-- Row Level Security
-- -----------------------------------------------------------------------------

ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_crud" ON public.employees
  FOR ALL TO authenticated
  USING (TRUE)
  WITH CHECK (TRUE);

