-- =============================================
-- SCHEMA: Interventions
-- DESCRIPTION: ...
-- =============================================
-- Enums
CREATE TYPE public.intervention_type AS enum(
  'new',
  'renovation',
  'maintenance'
);

CREATE TYPE public.intervention_status AS enum(
  'not_started',
  'in_progress',
  'completed',
  'cancelled'
);

CREATE TABLE public.interventions(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  inserted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  type public.intervention_type NOT NULL,
  status public.intervention_status NOT NULL,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  description text NOT NULL,
  property_id bigint NOT NULL,
  ticket_id bigint,
  rank text NOT NULL,
  CONSTRAINT pk_interventions PRIMARY KEY (id),
  CONSTRAINT fk_interventions_property_id FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE CASCADE,
  CONSTRAINT fk_interventions_ticket_id FOREIGN KEY (ticket_id) REFERENCES public.tickets(id),
  CONSTRAINT uq_interventions_status_rank UNIQUE (status, rank)
);

CREATE TABLE public.intervention_payments(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  inserted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  intervention_id bigint NOT NULL,
  movement_id bigint NOT NULL,
  CONSTRAINT pk_intervention_payments PRIMARY KEY (id),
  CONSTRAINT fk_intervention_payments_intervention_id FOREIGN KEY (intervention_id) REFERENCES public.interventions(id) ON DELETE CASCADE,
  CONSTRAINT fk_intervention_payments_movement_id FOREIGN KEY (movement_id) REFERENCES public.movements(id)
);

-- Views
CREATE VIEW public.intervention_payments_view AS
SELECT
  ip.intervention_id,
  ip.id,
  m.value,
  m.date,
  m.description
FROM
  public.intervention_payments ip
  JOIN public.movements m ON ip.movement_id = m.id;

-- Functions
CREATE FUNCTION public.insert_intervention_payment()
  RETURNS TRIGGER
  AS $$
DECLARE
  movement_id bigint;
BEGIN
  INSERT INTO public.movements(type, value, date, description)
    VALUES ('intervention'::public.movement_type, NEW.value, NEW.date, NEW.description)
  RETURNING
    id INTO movement_id;
  INSERT INTO public.intervention_payments(intervention_id, movement_id)
    VALUES (NEW.intervention_id, movement_id);
  RETURN new;
END;
$$
LANGUAGE plpgsql;

CREATE FUNCTION public.remove_intervention_payment()
  RETURNS TRIGGER
  AS $$
BEGIN
  DELETE FROM public.intervention_payments
  WHERE id = OLD.id;
  DELETE FROM public.movements
  WHERE id = OLD.movement_id;
  RETURN old;
END;
$$
LANGUAGE plpgsql;

-- Triggers
CREATE TRIGGER insert_intervention_payment
  INSTEAD OF insert ON public.intervention_payments_view
  FOR EACH ROW
  EXECUTE PROCEDURE public.insert_intervention_payment();

CREATE TRIGGER remove_intervention_payment
  INSTEAD OF DELETE ON public.intervention_payments_view
  FOR EACH ROW
  EXECUTE PROCEDURE public.remove_intervention_payment();

