-- =============================================================================
-- Movements
-- Financial movements shared across contracts and interventions.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Enums
-- -----------------------------------------------------------------------------

CREATE TYPE public.movement_type AS ENUM(
  'rent',
  'installment_amortization',
  'installment_interest',
  'intervention',
  'other'
);

-- -----------------------------------------------------------------------------
-- Tables
-- -----------------------------------------------------------------------------

CREATE TABLE public.movements(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by uuid REFERENCES public.users(id),
  updated_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by uuid REFERENCES public.users(id),
  type public.movement_type NOT NULL,
  occurred_at timestamp with time zone NOT NULL,
  value numeric(15, 2) NOT NULL,
  tax_id_number text,
  description text,
  CONSTRAINT pk_movements PRIMARY KEY (id)
);

CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.movements
  FOR EACH ROW
  EXECUTE PROCEDURE moddatetime(updated_at);

CREATE TRIGGER handle_audit_columns
  BEFORE INSERT OR UPDATE ON public.movements
  FOR EACH ROW
  EXECUTE PROCEDURE handle_audit_columns();

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

CREATE INDEX idx_movements_tax_id_number ON public.movements(tax_id_number)
  WHERE tax_id_number IS NOT NULL;

-- -----------------------------------------------------------------------------
-- Grants
-- -----------------------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON public.movements TO authenticated, service_role;

-- -----------------------------------------------------------------------------
-- Row Level Security
-- -----------------------------------------------------------------------------

ALTER TABLE public.movements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_crud" ON public.movements
  FOR ALL TO authenticated
  USING (TRUE)
  WITH CHECK (TRUE);

