-- =============================================
-- SCHEMA: Movements
-- DESCRIPTION: ...
-- =============================================
-- Enums
CREATE TYPE public.movement_type AS enum(
  'rent',
  'installment_amortization',
  'installment_interest',
  'intervention',
  'other'
);

-- Tables
CREATE TABLE public.movements(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inserted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  type movement_type NOT NULL,
  date timestamp with time zone NOT NULL,
  value double precision NOT NULL,
  tax_id_number text,
  description text
);

