-- =============================================
-- SCHEMA: Properties
-- DESCRIPTION: ...
-- =============================================
-- Enums
CREATE TYPE public.property_class AS enum(
  'urban',
  'rustic'
);

CREATE TYPE public.property_type AS enum(
  'building',
  'terrain',
  'house',
  'garages',
  'apartment',
  'store',
  'garage'
);

-- Tables
CREATE TABLE public.properties(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  inserted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  class public.property_class NOT NULL,
  type public.property_type NOT NULL,
  matrix text NOT NULL,
  conservatory text NOT NULL,
  area double precision,
  tipology text,
  fraction text,
  description text,
  patrimonial_value double precision,
  market_value double precision,
  address_id bigint NOT NULL,
  sold boolean NOT NULL DEFAULT FALSE,
  parent_id bigint,
  CONSTRAINT pk_properties PRIMARY KEY (id),
  CONSTRAINT fk_properties_address_id FOREIGN KEY (address_id) REFERENCES public.addresses(id),
  CONSTRAINT fk_properties_parent_id FOREIGN KEY (parent_id) REFERENCES public.properties(id) ON DELETE CASCADE,
  CONSTRAINT ck_properties_parent_id_not_self CHECK (parent_id IS NULL OR parent_id <> id),
  CONSTRAINT ck_properties_fraction_required_with_parent CHECK (parent_id IS NULL OR nullif(trim(fraction), '') IS NOT NULL)
);

-- Functions
CREATE FUNCTION public.validate_property_parent()
  RETURNS TRIGGER
  AS $$
DECLARE
  parent_type public.property_type;
BEGIN
  IF NEW.parent_id IS NULL THEN
    IF NEW.type NOT IN ('building'::public.property_type, 'garages'::public.property_type) AND EXISTS (
      SELECT
        1
      FROM
        public.properties
      WHERE
        parent_id = NEW.id) THEN
      RAISE EXCEPTION 'property type % cannot have fractions', NEW.type;
    END IF;
    RETURN NEW;
  END IF;
  SELECT
    type INTO parent_type
  FROM
    public.properties
  WHERE
    id = NEW.parent_id;
  IF parent_type IS NULL THEN
    RAISE EXCEPTION 'parent property % does not exist', NEW.parent_id;
  END IF;
  IF parent_type NOT IN ('building'::public.property_type, 'garages'::public.property_type) THEN
    RAISE EXCEPTION 'property type % cannot have fractions', parent_type;
  END IF;
  RETURN NEW;
END;
$$
LANGUAGE plpgsql;

-- Triggers
CREATE TRIGGER validate_property_parent
  BEFORE INSERT OR UPDATE ON public.properties
  FOR EACH ROW
  EXECUTE PROCEDURE public.validate_property_parent();

