-- =============================================================================
-- Properties
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Enums
-- -----------------------------------------------------------------------------

CREATE TYPE public.property_class AS ENUM(
  'urban',
  'rustic'
);

CREATE TYPE public.property_type AS ENUM(
  'building',
  'terrain',
  'house',
  'garages',
  'apartment',
  'store',
  'garage'
);

-- -----------------------------------------------------------------------------
-- Tables
-- -----------------------------------------------------------------------------

CREATE TABLE public.properties(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by uuid REFERENCES public.users(id),
  updated_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by uuid REFERENCES public.users(id),
  class public.property_class NOT NULL,
  type public.property_type NOT NULL,
  matrix text NOT NULL,
  conservatory text NOT NULL,
  area numeric(15, 2),
  tipology text,
  fraction text,
  description text,
  patrimonial_value numeric(15, 2),
  market_value numeric(15, 2),
  address_id bigint NOT NULL,
  sold boolean NOT NULL DEFAULT FALSE,
  parent_id bigint,
  CONSTRAINT pk_properties PRIMARY KEY (id),
  CONSTRAINT fk_properties_address_id FOREIGN KEY (address_id) REFERENCES public.addresses(id),
  CONSTRAINT fk_properties_parent_id FOREIGN KEY (parent_id) REFERENCES public.properties(id) ON DELETE CASCADE,
  CONSTRAINT ck_properties_parent_id_not_self CHECK (parent_id IS NULL OR parent_id <> id),
  CONSTRAINT ck_properties_fraction_required_with_parent CHECK (parent_id IS NULL OR NULLIF(TRIM(fraction), '') IS NOT NULL)
);

CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.properties
  FOR EACH ROW
  EXECUTE PROCEDURE moddatetime(updated_at);

CREATE TRIGGER handle_audit_columns
  BEFORE INSERT OR UPDATE ON public.properties
  FOR EACH ROW
  EXECUTE PROCEDURE handle_audit_columns();

-- -----------------------------------------------------------------------------
-- Functions
-- -----------------------------------------------------------------------------

CREATE FUNCTION public.validate_property_parent()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path = ''
  AS $$
DECLARE
  parent_type public.property_type;
BEGIN
  IF NEW.parent_id IS NULL THEN
    IF NEW.type NOT IN ('building'::public.property_type, 'garages'::public.property_type) AND EXISTS (
      SELECT
        1
      FROM
        public.properties
      WHERE
        parent_id = NEW.id) THEN
      RAISE EXCEPTION 'property type % cannot have fractions', NEW.type;
    END IF;
    RETURN NEW;
  END IF;
  SELECT
    type INTO parent_type
  FROM
    public.properties
  WHERE
    id = NEW.parent_id;
  IF parent_type IS NULL THEN
    RAISE EXCEPTION 'parent property % does not exist', NEW.parent_id;
  END IF;
  IF parent_type NOT IN ('building'::public.property_type, 'garages'::public.property_type) THEN
    RAISE EXCEPTION 'property type % cannot have fractions', parent_type;
  END IF;
  RETURN NEW;
END;
$$;

-- -----------------------------------------------------------------------------
-- Triggers
-- -----------------------------------------------------------------------------

CREATE TRIGGER validate_property_parent
  BEFORE INSERT OR UPDATE ON public.properties
  FOR EACH ROW
  EXECUTE PROCEDURE public.validate_property_parent();

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

CREATE INDEX idx_properties_address_id ON public.properties(address_id);

CREATE INDEX idx_properties_parent_id ON public.properties(parent_id);

-- -----------------------------------------------------------------------------
-- Grants
-- -----------------------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON public.properties TO authenticated, service_role;

-- -----------------------------------------------------------------------------
-- Row Level Security
-- -----------------------------------------------------------------------------

ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_crud" ON public.properties
  FOR ALL TO authenticated
  USING (TRUE)
  WITH CHECK (TRUE);

