-- =============================================
-- SCHEMA: Tenants
-- DESCRIPTION: ...
-- =============================================
-- Tables
CREATE TABLE public.tenants(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  inserted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  name text NOT NULL,
  gender public.gender NOT NULL,
  marital_status public.marital_status NOT NULL,
  nationality text NOT NULL,
  birth_date timestamp with time zone,
  id_type text NOT NULL,
  id_expiration_date timestamp with time zone,
  id_number text NOT NULL,
  tax_id_number text NOT NULL,
  address_id bigint NOT NULL,
  email text,
  mobile text,
  phone text,
  CONSTRAINT pk_tenants PRIMARY KEY (id),
  CONSTRAINT fk_tenants_address_id FOREIGN KEY (address_id) REFERENCES public.addresses(id)
);

