-- =============================================================================
-- Tenants
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Tables
-- -----------------------------------------------------------------------------

CREATE TABLE public.tenants(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by uuid REFERENCES public.users(id),
  updated_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by uuid REFERENCES public.users(id),
  name text NOT NULL,
  gender public.gender NOT NULL,
  marital_status public.marital_status NOT NULL,
  nationality text NOT NULL,
  birth_date date,
  id_type text NOT NULL,
  id_expiration_date date,
  id_number text NOT NULL,
  tax_id_number text NOT NULL,
  address_id bigint NOT NULL,
  email text,
  mobile text,
  phone text,
  CONSTRAINT pk_tenants PRIMARY KEY (id),
  CONSTRAINT fk_tenants_address_id FOREIGN KEY (address_id) REFERENCES public.addresses(id),
  CONSTRAINT uq_tenants_tax_id_number UNIQUE (tax_id_number)
);

CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.tenants
  FOR EACH ROW
  EXECUTE PROCEDURE moddatetime(updated_at);

CREATE TRIGGER handle_audit_columns
  BEFORE INSERT OR UPDATE ON public.tenants
  FOR EACH ROW
  EXECUTE PROCEDURE handle_audit_columns();

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

CREATE INDEX idx_tenants_address_id ON public.tenants(address_id);

-- -----------------------------------------------------------------------------
-- Grants
-- -----------------------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON public.tenants TO authenticated, service_role;

-- -----------------------------------------------------------------------------
-- Row Level Security
-- -----------------------------------------------------------------------------

ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_crud" ON public.tenants
  FOR ALL TO authenticated
  USING (TRUE)
  WITH CHECK (TRUE);

