-- =============================================
-- SCHEMA: Tenants
-- DESCRIPTION: ...
-- =============================================
-- Tables
CREATE TABLE public.tenants(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inserted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  name text NOT NULL,
  gender gender NOT NULL,
  marital_status marital_status NOT NULL,
  nationality text NOT NULL,
  birth_date timestamp with time zone,
  id_type text NOT NULL,
  id_expiration_date timestamp with time zone,
  id_number text NOT NULL,
  tax_id_number text NOT NULL,
  country text,
  region text,
  address text,
  postal_code text,
  city text,
  email text,
  mobile text,
  phone text
);

