-- =============================================
-- SCHEMA: Tickets
-- DESCRIPTION: ...
-- =============================================
-- Enums
CREATE TYPE public.ticket_priority AS enum(
  'low',
  'medium',
  'high'
);

CREATE TYPE public.ticket_status AS enum(
  'open',
  'in_progress',
  'resolved',
  'cancelled'
);

CREATE TABLE public.tickets(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  inserted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  date timestamp with time zone NOT NULL,
  priority public.ticket_priority NOT NULL,
  status public.ticket_status NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  property_id bigint NOT NULL,
  rank text NOT NULL,
  CONSTRAINT pk_tickets PRIMARY KEY (id),
  CONSTRAINT fk_tickets_property_id FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE CASCADE
);

