-- =============================================================================
-- Tickets
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Enums
-- -----------------------------------------------------------------------------

CREATE TYPE public.ticket_priority AS ENUM(
  'low',
  'medium',
  'high'
);

CREATE TYPE public.ticket_status AS ENUM(
  'open',
  'in_progress',
  'resolved',
  'cancelled'
);

-- -----------------------------------------------------------------------------
-- Tables
-- -----------------------------------------------------------------------------

CREATE TABLE public.tickets(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by uuid REFERENCES public.users(id),
  updated_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_by uuid REFERENCES public.users(id),
  priority public.ticket_priority NOT NULL,
  status public.ticket_status NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  property_id bigint NOT NULL,
  rank text COLLATE "C" NOT NULL,
  CONSTRAINT pk_tickets PRIMARY KEY (id),
  CONSTRAINT fk_tickets_property_id FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE CASCADE,
  CONSTRAINT uq_tickets_status_rank UNIQUE (status, rank)
);

CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.tickets
  FOR EACH ROW
  EXECUTE PROCEDURE moddatetime(updated_at);

CREATE TRIGGER handle_audit_columns
  BEFORE INSERT OR UPDATE ON public.tickets
  FOR EACH ROW
  EXECUTE PROCEDURE handle_audit_columns();

CREATE TABLE public.ticket_status_transitions(
  from_status public.ticket_status NOT NULL,
  to_status public.ticket_status NOT NULL,
  CONSTRAINT pk_ticket_status_transitions PRIMARY KEY (from_status, to_status)
);

INSERT INTO public.ticket_status_transitions(from_status, to_status)
VALUES
  ('open', 'in_progress'),
  ('open', 'cancelled'),
  ('in_progress', 'open'),
  ('in_progress', 'resolved'),
  ('in_progress', 'cancelled'),
  ('resolved', 'open'),
  ('resolved', 'cancelled'),
  ('cancelled', 'open');

CREATE TABLE public.ticket_status_history(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp with time zone NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  created_by uuid REFERENCES public.users(id),
  ticket_id bigint NOT NULL,
  from_status public.ticket_status,
  to_status public.ticket_status NOT NULL,
  CONSTRAINT pk_ticket_status_history PRIMARY KEY (id),
  CONSTRAINT fk_ticket_status_history_ticket_id FOREIGN KEY (ticket_id) REFERENCES public.tickets(id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Functions
-- -----------------------------------------------------------------------------

CREATE FUNCTION public.record_initial_ticket_status()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path = ''
  AS $$
BEGIN
  INSERT INTO public.ticket_status_history(ticket_id, from_status, to_status, created_by)
    VALUES (NEW.id, NULL, NEW.status, NEW.created_by);
  RETURN NEW;
END;
$$;

CREATE FUNCTION public.transition_ticket(
  p_ticket_id bigint,
  p_to_status public.ticket_status,
  p_rank text
)
  RETURNS public.tickets
  LANGUAGE plpgsql
  SECURITY INVOKER
  SET search_path = ''
  AS $$
DECLARE
  v_ticket public.tickets;
BEGIN
  IF p_rank IS NULL OR p_rank = '' THEN
    RAISE EXCEPTION 'Rank is required';
  END IF;
  SELECT
    *
  INTO v_ticket
  FROM
    public.tickets
  WHERE
    id = p_ticket_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Ticket not found: %', p_ticket_id;
  END IF;
  IF v_ticket.status IS NOT DISTINCT FROM p_to_status AND v_ticket.rank IS NOT DISTINCT FROM p_rank THEN
    RETURN v_ticket;
  END IF;
  IF v_ticket.status IS DISTINCT FROM p_to_status THEN
    IF NOT EXISTS (
      SELECT
        1
      FROM
        public.ticket_status_transitions
      WHERE
        from_status = v_ticket.status
        AND to_status = p_to_status) THEN
      RAISE EXCEPTION 'Invalid ticket status transition from % to %', v_ticket.status, p_to_status;
    END IF;
    INSERT INTO public.ticket_status_history(ticket_id, from_status, to_status, created_by)
      VALUES (p_ticket_id, v_ticket.status, p_to_status,(SELECT auth.uid()));
  END IF;
  UPDATE
    public.tickets
  SET
    status = p_to_status,
    rank = p_rank
  WHERE
    id = p_ticket_id;
  SELECT
    *
  INTO v_ticket
  FROM
    public.tickets
  WHERE
    id = p_ticket_id;
  RETURN v_ticket;
END;
$$;

-- -----------------------------------------------------------------------------
-- Triggers
-- -----------------------------------------------------------------------------

CREATE TRIGGER record_initial_ticket_status
  AFTER INSERT ON public.tickets
  FOR EACH ROW
  EXECUTE PROCEDURE public.record_initial_ticket_status();

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

CREATE INDEX idx_tickets_property_id ON public.tickets(property_id);

CREATE INDEX idx_ticket_status_history_ticket_id_created_at ON public.ticket_status_history(ticket_id, created_at);

CREATE INDEX idx_ticket_status_history_ticket_id_to_status_created_at ON public.ticket_status_history(ticket_id, to_status, created_at);

-- -----------------------------------------------------------------------------
-- Grants
-- -----------------------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON public.tickets TO authenticated, service_role;
GRANT SELECT ON public.ticket_status_transitions TO authenticated, service_role;
GRANT SELECT, INSERT ON public.ticket_status_history TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.transition_ticket(bigint, public.ticket_status, text) TO authenticated, service_role;

-- -----------------------------------------------------------------------------
-- Row Level Security
-- -----------------------------------------------------------------------------

ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_crud" ON public.tickets
  FOR ALL TO authenticated
  USING (TRUE)
  WITH CHECK (TRUE);

ALTER TABLE public.ticket_status_transitions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_select" ON public.ticket_status_transitions
  FOR SELECT TO authenticated
  USING (TRUE);

ALTER TABLE public.ticket_status_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_select" ON public.ticket_status_history
  FOR SELECT TO authenticated
  USING (TRUE);

CREATE POLICY "authenticated_insert" ON public.ticket_status_history
  FOR INSERT TO authenticated
  WITH CHECK (TRUE);
