-- =============================================
-- SCHEMA: Tickets
-- DESCRIPTION: ...
-- =============================================
-- Enums
CREATE TYPE public.ticket_priority AS enum(
  'low',
  'medium',
  'high'
);

CREATE TYPE public.ticket_status AS enum(
  'open',
  'in_progress',
  'resolved',
  'cancelled'
);

CREATE TABLE public.tickets(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inserted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  date timestamp with time zone NOT NULL,
  priority ticket_priority NOT NULL,
  status ticket_status NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  property_id bigint NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  fraction_id bigint REFERENCES fractions(id)
);

