-- =============================================
-- SCHEMA: Vendors
-- DESCRIPTION: ...
-- =============================================
-- Tables
CREATE TABLE public.vendors(
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  inserted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  name text NOT NULL,
  tax_id_number text NOT NULL,
  description text,
  tags text[] NOT NULL DEFAULT '{}' ::text[],
  address_id bigint NOT NULL,
  email text,
  mobile text,
  phone text,
  website text,
  CONSTRAINT pk_vendors PRIMARY KEY (id),
  CONSTRAINT fk_vendors_address_id FOREIGN KEY (address_id) REFERENCES public.addresses(id)
);

