create extension if not exists "pg_cron" with schema "pg_catalog";

create extension if not exists "moddatetime" with schema "extensions";

create type "public"."contract_type" as enum ('renting', 'lending');

create type "public"."gender" as enum ('male', 'female', 'other');

create type "public"."intervention_status" as enum ('not_started', 'in_progress', 'completed', 'cancelled');

create type "public"."intervention_type" as enum ('new', 'renovation', 'maintenance');

create type "public"."marital_status" as enum ('single', 'married', 'union', 'divorced', 'widowed');

create type "public"."movement_type" as enum ('rent', 'installment_amortization', 'installment_interest', 'intervention', 'other');

create type "public"."property_class" as enum ('urban', 'rustic');

create type "public"."property_type" as enum ('building', 'terrain', 'house', 'garages', 'apartment', 'store', 'garage');

create type "public"."salary_type" as enum ('hourly', 'monthly');

create type "public"."ticket_priority" as enum ('low', 'medium', 'high');

create type "public"."ticket_status" as enum ('open', 'in_progress', 'resolved', 'cancelled');


  create table "public"."addresses" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "country" text,
    "region" text,
    "address" text,
    "postal_code" text,
    "city" text
      );



  create table "public"."contracts" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "type" public.contract_type not null,
    "start_date" timestamp with time zone not null,
    "end_date" timestamp with time zone,
    "property_id" bigint not null,
    "is_active" boolean not null default true
      );



  create table "public"."contracts_tenants" (
    "contract_id" bigint not null,
    "tenant_id" bigint not null
      );



  create table "public"."due_notes" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "contract_id" bigint not null,
    "due_date" timestamp with time zone not null,
    "value" double precision not null
      );



  create table "public"."employees" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "name" text not null,
    "gender" public.gender not null,
    "marital_status" public.marital_status not null,
    "nationality" text not null,
    "birth_date" timestamp with time zone,
    "id_type" text not null,
    "id_expiration_date" timestamp with time zone,
    "id_number" text not null,
    "tax_id_number" text not null,
    "ss_number" text not null,
    "address_id" bigint,
    "email" text,
    "mobile" text,
    "phone" text,
    "position" text not null,
    "salary_type" public.salary_type not null,
    "salary" double precision not null
      );



  create table "public"."installment_payments" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "contract_id" bigint not null,
    "interest_movement_id" bigint not null,
    "amortization_movement_id" bigint,
    "extra_debt" double precision
      );



  create table "public"."installment_updates" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "update_date" timestamp with time zone not null,
    "installment" double precision not null,
    "interest" double precision not null,
    "contract_id" bigint not null
      );



  create table "public"."intervention_payments" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "intervention_id" bigint not null,
    "movement_id" bigint not null
      );



  create table "public"."interventions" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "type" public.intervention_type not null,
    "status" public.intervention_status not null,
    "start_date" timestamp with time zone,
    "end_date" timestamp with time zone,
    "description" text not null,
    "property_id" bigint not null,
    "ticket_id" bigint
      );



  create table "public"."lending_contracts" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "contract_type" public.contract_type not null generated always as ('lending'::public.contract_type) stored,
    "sale_value" double precision not null,
    "down_payment" double precision not null,
    "yearly_raise" double precision not null
      );



  create table "public"."movements" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "type" public.movement_type not null,
    "date" timestamp with time zone not null,
    "value" double precision not null,
    "tax_id_number" text,
    "description" text
      );



  create table "public"."profiles" (
    "id" uuid not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "email" text not null,
    "display_name" text not null,
    "image" text
      );



  create table "public"."properties" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "class" public.property_class not null,
    "type" public.property_type not null,
    "matrix" text not null,
    "conservatory" text not null,
    "area" double precision,
    "tipology" text,
    "fraction" text,
    "description" text,
    "patrimonial_value" double precision,
    "market_value" double precision,
    "address_id" bigint not null,
    "sold" boolean not null default false,
    "parent_id" bigint
      );



  create table "public"."rent_payments" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "contract_id" bigint not null,
    "movement_id" bigint not null
      );



  create table "public"."rent_updates" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "update_date" timestamp with time zone not null,
    "rent" double precision not null,
    "contract_id" bigint not null
      );



  create table "public"."renting_contracts" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "contract_type" public.contract_type not null generated always as ('renting'::public.contract_type) stored
      );



  create table "public"."tenants" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "name" text not null,
    "gender" public.gender not null,
    "marital_status" public.marital_status not null,
    "nationality" text not null,
    "birth_date" timestamp with time zone,
    "id_type" text not null,
    "id_expiration_date" timestamp with time zone,
    "id_number" text not null,
    "tax_id_number" text not null,
    "address_id" bigint,
    "email" text,
    "mobile" text,
    "phone" text
      );



  create table "public"."tickets" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "date" timestamp with time zone not null,
    "priority" public.ticket_priority not null,
    "status" public.ticket_status not null,
    "title" text not null,
    "description" text not null,
    "property_id" bigint not null
      );



  create table "public"."vendors" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "name" text not null,
    "tax_id_number" text not null,
    "description" text,
    "tags" text[] not null default '{}'::text[],
    "address_id" bigint,
    "email" text,
    "mobile" text,
    "phone" text,
    "website" text
      );


CREATE UNIQUE INDEX pk_addresses ON public.addresses USING btree (id);

CREATE UNIQUE INDEX pk_contracts ON public.contracts USING btree (id);

CREATE UNIQUE INDEX pk_contracts_tenants ON public.contracts_tenants USING btree (contract_id, tenant_id);

CREATE UNIQUE INDEX pk_due_notes ON public.due_notes USING btree (id);

CREATE UNIQUE INDEX pk_employees ON public.employees USING btree (id);

CREATE UNIQUE INDEX pk_installment_payments ON public.installment_payments USING btree (id);

CREATE UNIQUE INDEX pk_installment_updates ON public.installment_updates USING btree (id);

CREATE UNIQUE INDEX pk_intervention_payments ON public.intervention_payments USING btree (id);

CREATE UNIQUE INDEX pk_interventions ON public.interventions USING btree (id);

CREATE UNIQUE INDEX pk_lending_contracts ON public.lending_contracts USING btree (id);

CREATE UNIQUE INDEX pk_movements ON public.movements USING btree (id);

CREATE UNIQUE INDEX pk_profiles ON public.profiles USING btree (id);

CREATE UNIQUE INDEX pk_properties ON public.properties USING btree (id);

CREATE UNIQUE INDEX pk_rent_payments ON public.rent_payments USING btree (id);

CREATE UNIQUE INDEX pk_rent_updates ON public.rent_updates USING btree (id);

CREATE UNIQUE INDEX pk_renting_contracts ON public.renting_contracts USING btree (id);

CREATE UNIQUE INDEX pk_tenants ON public.tenants USING btree (id);

CREATE UNIQUE INDEX pk_tickets ON public.tickets USING btree (id);

CREATE UNIQUE INDEX pk_vendors ON public.vendors USING btree (id);

CREATE UNIQUE INDEX uq_contracts_id_type ON public.contracts USING btree (id, type);

CREATE UNIQUE INDEX uq_contracts_property_id_is_active ON public.contracts USING btree (property_id, is_active);

alter table "public"."addresses" add constraint "pk_addresses" PRIMARY KEY using index "pk_addresses";

alter table "public"."contracts" add constraint "pk_contracts" PRIMARY KEY using index "pk_contracts";

alter table "public"."contracts_tenants" add constraint "pk_contracts_tenants" PRIMARY KEY using index "pk_contracts_tenants";

alter table "public"."due_notes" add constraint "pk_due_notes" PRIMARY KEY using index "pk_due_notes";

alter table "public"."employees" add constraint "pk_employees" PRIMARY KEY using index "pk_employees";

alter table "public"."installment_payments" add constraint "pk_installment_payments" PRIMARY KEY using index "pk_installment_payments";

alter table "public"."installment_updates" add constraint "pk_installment_updates" PRIMARY KEY using index "pk_installment_updates";

alter table "public"."intervention_payments" add constraint "pk_intervention_payments" PRIMARY KEY using index "pk_intervention_payments";

alter table "public"."interventions" add constraint "pk_interventions" PRIMARY KEY using index "pk_interventions";

alter table "public"."lending_contracts" add constraint "pk_lending_contracts" PRIMARY KEY using index "pk_lending_contracts";

alter table "public"."movements" add constraint "pk_movements" PRIMARY KEY using index "pk_movements";

alter table "public"."profiles" add constraint "pk_profiles" PRIMARY KEY using index "pk_profiles";

alter table "public"."properties" add constraint "pk_properties" PRIMARY KEY using index "pk_properties";

alter table "public"."rent_payments" add constraint "pk_rent_payments" PRIMARY KEY using index "pk_rent_payments";

alter table "public"."rent_updates" add constraint "pk_rent_updates" PRIMARY KEY using index "pk_rent_updates";

alter table "public"."renting_contracts" add constraint "pk_renting_contracts" PRIMARY KEY using index "pk_renting_contracts";

alter table "public"."tenants" add constraint "pk_tenants" PRIMARY KEY using index "pk_tenants";

alter table "public"."tickets" add constraint "pk_tickets" PRIMARY KEY using index "pk_tickets";

alter table "public"."vendors" add constraint "pk_vendors" PRIMARY KEY using index "pk_vendors";

alter table "public"."contracts" add constraint "fk_contracts_property_id" FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE CASCADE not valid;

alter table "public"."contracts" validate constraint "fk_contracts_property_id";

alter table "public"."contracts" add constraint "uq_contracts_id_type" UNIQUE using index "uq_contracts_id_type";

alter table "public"."contracts" add constraint "uq_contracts_property_id_is_active" UNIQUE using index "uq_contracts_property_id_is_active";

alter table "public"."contracts_tenants" add constraint "fk_contracts_tenants_contract_id" FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON DELETE CASCADE not valid;

alter table "public"."contracts_tenants" validate constraint "fk_contracts_tenants_contract_id";

alter table "public"."contracts_tenants" add constraint "fk_contracts_tenants_tenant_id" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE not valid;

alter table "public"."contracts_tenants" validate constraint "fk_contracts_tenants_tenant_id";

alter table "public"."due_notes" add constraint "fk_due_notes_contract_id" FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON DELETE CASCADE not valid;

alter table "public"."due_notes" validate constraint "fk_due_notes_contract_id";

alter table "public"."employees" add constraint "fk_employees_address_id" FOREIGN KEY (address_id) REFERENCES public.addresses(id) not valid;

alter table "public"."employees" validate constraint "fk_employees_address_id";

alter table "public"."installment_payments" add constraint "fk_installment_payments_amortization_movement_id" FOREIGN KEY (amortization_movement_id) REFERENCES public.movements(id) not valid;

alter table "public"."installment_payments" validate constraint "fk_installment_payments_amortization_movement_id";

alter table "public"."installment_payments" add constraint "fk_installment_payments_contract_id" FOREIGN KEY (contract_id) REFERENCES public.lending_contracts(id) ON DELETE CASCADE not valid;

alter table "public"."installment_payments" validate constraint "fk_installment_payments_contract_id";

alter table "public"."installment_payments" add constraint "fk_installment_payments_interest_movement_id" FOREIGN KEY (interest_movement_id) REFERENCES public.movements(id) not valid;

alter table "public"."installment_payments" validate constraint "fk_installment_payments_interest_movement_id";

alter table "public"."installment_updates" add constraint "fk_installment_updates_contract_id" FOREIGN KEY (contract_id) REFERENCES public.lending_contracts(id) ON DELETE CASCADE not valid;

alter table "public"."installment_updates" validate constraint "fk_installment_updates_contract_id";

alter table "public"."intervention_payments" add constraint "fk_intervention_payments_intervention_id" FOREIGN KEY (intervention_id) REFERENCES public.interventions(id) ON DELETE CASCADE not valid;

alter table "public"."intervention_payments" validate constraint "fk_intervention_payments_intervention_id";

alter table "public"."intervention_payments" add constraint "fk_intervention_payments_movement_id" FOREIGN KEY (movement_id) REFERENCES public.movements(id) not valid;

alter table "public"."intervention_payments" validate constraint "fk_intervention_payments_movement_id";

alter table "public"."interventions" add constraint "fk_interventions_property_id" FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE CASCADE not valid;

alter table "public"."interventions" validate constraint "fk_interventions_property_id";

alter table "public"."interventions" add constraint "fk_interventions_ticket_id" FOREIGN KEY (ticket_id) REFERENCES public.tickets(id) not valid;

alter table "public"."interventions" validate constraint "fk_interventions_ticket_id";

alter table "public"."lending_contracts" add constraint "fk_lending_contracts_id_contract_type" FOREIGN KEY (id, contract_type) REFERENCES public.contracts(id, type) ON DELETE CASCADE not valid;

alter table "public"."lending_contracts" validate constraint "fk_lending_contracts_id_contract_type";

alter table "public"."profiles" add constraint "fk_profiles_id" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."profiles" validate constraint "fk_profiles_id";

alter table "public"."properties" add constraint "ck_properties_fraction_required_with_parent" CHECK (((parent_id IS NULL) OR (NULLIF(TRIM(BOTH FROM fraction), ''::text) IS NOT NULL))) not valid;

alter table "public"."properties" validate constraint "ck_properties_fraction_required_with_parent";

alter table "public"."properties" add constraint "ck_properties_parent_id_not_self" CHECK (((parent_id IS NULL) OR (parent_id <> id))) not valid;

alter table "public"."properties" validate constraint "ck_properties_parent_id_not_self";

alter table "public"."properties" add constraint "fk_properties_address_id" FOREIGN KEY (address_id) REFERENCES public.addresses(id) not valid;

alter table "public"."properties" validate constraint "fk_properties_address_id";

alter table "public"."properties" add constraint "fk_properties_parent_id" FOREIGN KEY (parent_id) REFERENCES public.properties(id) ON DELETE CASCADE not valid;

alter table "public"."properties" validate constraint "fk_properties_parent_id";

alter table "public"."rent_payments" add constraint "fk_rent_payments_contract_id" FOREIGN KEY (contract_id) REFERENCES public.renting_contracts(id) ON DELETE CASCADE not valid;

alter table "public"."rent_payments" validate constraint "fk_rent_payments_contract_id";

alter table "public"."rent_payments" add constraint "fk_rent_payments_movement_id" FOREIGN KEY (movement_id) REFERENCES public.movements(id) not valid;

alter table "public"."rent_payments" validate constraint "fk_rent_payments_movement_id";

alter table "public"."rent_updates" add constraint "fk_rent_updates_contract_id" FOREIGN KEY (contract_id) REFERENCES public.renting_contracts(id) ON DELETE CASCADE not valid;

alter table "public"."rent_updates" validate constraint "fk_rent_updates_contract_id";

alter table "public"."renting_contracts" add constraint "fk_renting_contracts_id_contract_type" FOREIGN KEY (id, contract_type) REFERENCES public.contracts(id, type) ON DELETE CASCADE not valid;

alter table "public"."renting_contracts" validate constraint "fk_renting_contracts_id_contract_type";

alter table "public"."tenants" add constraint "fk_tenants_address_id" FOREIGN KEY (address_id) REFERENCES public.addresses(id) not valid;

alter table "public"."tenants" validate constraint "fk_tenants_address_id";

alter table "public"."tickets" add constraint "fk_tickets_property_id" FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE CASCADE not valid;

alter table "public"."tickets" validate constraint "fk_tickets_property_id";

alter table "public"."vendors" add constraint "fk_vendors_address_id" FOREIGN KEY (address_id) REFERENCES public.addresses(id) not valid;

alter table "public"."vendors" validate constraint "fk_vendors_address_id";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.profiles(id, email, display_name)
    VALUES(NEW.id, NEW.email, NEW.raw_user_meta_data ->> 'display_name');
  RETURN new;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.insert_contract()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  contract_id bigint;
  inserted_contract contracts_view % ROWTYPE;
BEGIN
  INSERT INTO contracts(type, start_date, end_date, property_id)
    VALUES (NEW.type, NEW.start_date, NEW.end_date, NEW.property_id)
  RETURNING
    id INTO contract_id;
  IF NEW.type = 'renting' THEN
    INSERT INTO renting_contracts(id)
      VALUES (contract_id);
    INSERT INTO rent_updates(contract_id, update_date, rent)
      VALUES (contract_id, NEW.start_date,(NEW.data ->> 'rent')::double precision);
  ELSIF NEW.type = 'lending' THEN
    INSERT INTO lending_contracts(id, sale_value, down_payment, yearly_raise)
      VALUES (contract_id,(NEW.data ->> 'sale_value')::double precision,(NEW.data ->> 'down_payment')::double precision,(NEW.data ->> 'yearly_raise')::double precision);
    INSERT INTO installment_updates(contract_id, update_date, installment, interest)
      VALUES (contract_id, NEW.start_date,(NEW.data ->> 'installment')::double precision,(NEW.data ->> 'interest')::double precision);
  END IF;
  SELECT
    * INTO inserted_contract
  FROM
    contracts_view
  WHERE
    id = contract_id;
  RETURN inserted_contract;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.insert_installment_payment()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  interest_movement_id bigint;
  DECLARE amortization_movement_id bigint;
BEGIN
  INSERT INTO movements(type, value, date, description)
    VALUES ('installment_interest'::movement_type, NEW.interest, NEW.date, NEW.description)
  RETURNING
    id INTO interest_movement_id;
  IF NEW.amortization > 0 THEN
    INSERT INTO movements(type, value, date, description)
      VALUES ('installment_amortization'::movement_type, NEW.amortization, NEW.date, NEW.description)
    RETURNING
      id INTO amortization_movement_id;
  END IF;
  INSERT INTO installment_payments(contract_id, interest_movement_id, amortization_movement_id, extra_debt)
    VALUES (NEW.contract_id, interest_movement_id, amortization_movement_id, NEW.extra_debt);
  RETURN new;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.insert_intervention_payment()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  movement_id bigint;
BEGIN
  INSERT INTO movements(type, value, date, description)
    VALUES ('intervention'::movement_type, NEW.value, NEW.date, NEW.description)
  RETURNING
    id INTO movement_id;
  INSERT INTO intervention_payments(intervention_id, movement_id)
    VALUES (NEW.intervention_id, movement_id);
  RETURN new;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.insert_rent_payment()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  movement_id bigint;
BEGIN
  INSERT INTO movements(type, value, date, description)
    VALUES ('rent'::movement_type, NEW.value, NEW.date, NEW.description)
  RETURNING
    id INTO movement_id;
  INSERT INTO rent_payments(contract_id, movement_id)
    VALUES (NEW.contract_id, movement_id);
  RETURN new;
END;
$function$
;

create or replace view "public"."installment_payments_view" as  SELECT ip.contract_id,
    ip.id,
    i.date,
    i.value AS interest,
    COALESCE(a.value, (0)::double precision) AS amortization,
    ip.extra_debt,
    i.description
   FROM ((public.installment_payments ip
     LEFT JOIN public.movements a ON ((ip.amortization_movement_id = a.id)))
     LEFT JOIN public.movements i ON ((ip.interest_movement_id = i.id)));


create or replace view "public"."intervention_payments_view" as  SELECT ip.intervention_id,
    ip.id,
    m.value,
    m.date,
    m.description
   FROM (public.intervention_payments ip
     JOIN public.movements m ON ((ip.movement_id = m.id)));


create or replace view "public"."lending_contracts_debts_view" as  SELECT lc.id,
    ((lc.sale_value - lc.down_payment) - COALESCE(sum(ip.amortization), (0)::double precision)) AS debt,
    COALESCE(( SELECT ip_1.extra_debt
           FROM public.installment_payments_view ip_1
          WHERE (ip_1.contract_id = lc.id)
          ORDER BY ip_1.date DESC
         LIMIT 1), (0)::double precision) AS extra_debt,
    max(ip.date) AS last_payment_date
   FROM (public.lending_contracts lc
     LEFT JOIN public.installment_payments_view ip ON ((lc.id = ip.contract_id)))
  GROUP BY lc.id;


create or replace view "public"."lending_contracts_view" as  SELECT lc.id,
    lc.inserted_at,
    lc.contract_type,
    lc.sale_value,
    lc.down_payment,
    lc.yearly_raise,
    lcd.debt,
    lcd.extra_debt,
    lcd.last_payment_date,
    COALESCE(active_updates.installment, (0)::double precision) AS installment,
    COALESCE(active_updates.interest, (0)::double precision) AS interest,
        CASE
            WHEN (last_updates.update_date IS NULL) THEN NULL::json
            ELSE json_build_object('update_date', last_updates.update_date, 'installment', COALESCE(last_updates.installment, (0)::double precision), 'interest', COALESCE(last_updates.interest, (0)::double precision))
        END AS next_update
   FROM (((public.lending_contracts lc
     LEFT JOIN public.lending_contracts_debts_view lcd ON ((lc.id = lcd.id)))
     LEFT JOIN ( SELECT DISTINCT ON (iu.contract_id) iu.contract_id,
            iu.installment,
            iu.interest,
            iu.update_date
           FROM public.installment_updates iu
          ORDER BY iu.contract_id, iu.inserted_at DESC) last_updates ON ((lc.id = last_updates.contract_id)))
     LEFT JOIN ( SELECT DISTINCT ON (iu.contract_id) iu.contract_id,
            iu.installment,
            iu.interest,
            iu.update_date
           FROM public.installment_updates iu
          WHERE (iu.update_date <= timezone('utc'::text, now()))
          ORDER BY iu.contract_id, iu.update_date DESC) active_updates ON ((lc.id = active_updates.contract_id)));


CREATE OR REPLACE FUNCTION public.remove_installment_payment()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  DELETE FROM installment_payments
  WHERE id = OLD.id;
  DELETE FROM movements
  WHERE id = OLD.interest_movement_id;
  DELETE FROM movements
  WHERE id = OLD.amortization_movement_id;
  RETURN old;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.remove_intervention_payment()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  DELETE FROM intervention_payments
  WHERE id = OLD.id;
  DELETE FROM movements
  WHERE id = OLD.movement_id;
  RETURN old;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.remove_rent_payment()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  DELETE FROM rent_payments
  WHERE id = OLD.id;
  DELETE FROM movements
  WHERE id = OLD.movement_id;
  RETURN old;
END;
$function$
;

create or replace view "public"."rent_payments_view" as  SELECT rp.contract_id,
    rp.id,
    m.value,
    m.date,
    m.description
   FROM (public.rent_payments rp
     JOIN public.movements m ON ((rp.movement_id = m.id)));


create or replace view "public"."renting_contracts_view" as  SELECT rc.id,
    rc.inserted_at,
    rc.contract_type,
    COALESCE(active_updates.rent, (0)::double precision) AS rent,
        CASE
            WHEN (next_updates.update_date IS NULL) THEN NULL::json
            ELSE json_build_object('update_date', next_updates.update_date, 'rent', next_updates.rent)
        END AS next_update
   FROM ((public.renting_contracts rc
     LEFT JOIN ( SELECT DISTINCT ON (ru.contract_id) ru.contract_id,
            ru.rent,
            ru.update_date
           FROM public.rent_updates ru
          WHERE (ru.update_date <= timezone('utc'::text, now()))
          ORDER BY ru.contract_id, ru.update_date DESC) active_updates ON ((rc.id = active_updates.contract_id)))
     LEFT JOIN ( SELECT DISTINCT ON (ru.contract_id) ru.contract_id,
            ru.rent,
            ru.update_date
           FROM public.rent_updates ru
          WHERE (ru.update_date > timezone('utc'::text, now()))
          ORDER BY ru.contract_id, ru.inserted_at DESC) next_updates ON ((rc.id = next_updates.contract_id)));


CREATE OR REPLACE FUNCTION public.update_contract()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  contract_id bigint;
  updated_contract contracts_view % rowtype;
BEGIN
  contract_id := NEW.id;
  UPDATE
    contracts
  SET
    start_date = NEW.start_date,
    end_date = NEW.end_date,
    property_id = NEW.property_id
  WHERE
    id = contract_id;
  IF NEW.type = 'renting' THEN
    INSERT INTO rent_updates(contract_id, update_date, rent)
      VALUES (contract_id, NEW.start_date,(NEW.data ->> 'rent')::double precision);
  ELSIF NEW.type = 'lending' THEN
    UPDATE
      lending_contracts
    SET
      sale_value =(NEW.data ->> 'sale_value')::double precision,
      down_payment =(NEW.data ->> 'down_payment')::double precision,
      yearly_raise =(NEW.data ->> 'yearly_raise')::double precision
    WHERE
      id = contract_id;
    INSERT INTO installment_updates(contract_id, update_date, installment, interest)
      VALUES (contract_id, NEW.start_date,(NEW.data ->> 'installment')::double precision,(NEW.data ->> 'interest')::double precision);
  END IF;
  SELECT
    * INTO updated_contract
  FROM
    contracts_view
  WHERE
    id = contract_id;
  RETURN updated_contract;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_contract_tenants(p_contract_id bigint, p_tenants bigint[])
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  DELETE FROM contracts_tenants
  WHERE contract_id = p_contract_id;
  INSERT INTO contracts_tenants(contract_id, tenant_id)
  SELECT
    p_contract_id,
    unnest(p_tenants);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.validate_property_parent()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  parent_type property_type;
BEGIN
  IF NEW.parent_id IS NULL THEN
    IF NEW.type NOT IN ('building'::property_type, 'garages'::property_type) AND EXISTS (
      SELECT
        1
      FROM
        public.properties
      WHERE
        parent_id = NEW.id) THEN
      RAISE EXCEPTION 'property type % cannot have fractions', NEW.type;
    END IF;
    RETURN NEW;
  END IF;
  SELECT
    type INTO parent_type
  FROM
    public.properties
  WHERE
    id = NEW.parent_id;
  IF parent_type IS NULL THEN
    RAISE EXCEPTION 'parent property % does not exist', NEW.parent_id;
  END IF;
  IF parent_type NOT IN ('building'::property_type, 'garages'::property_type) THEN
    RAISE EXCEPTION 'property type % cannot have fractions', parent_type;
  END IF;
  RETURN NEW;
END;
$function$
;

create or replace view "public"."contracts_accounts_view" as  SELECT dn.contract_id,
    dn.id,
    'due_note'::text AS type,
    dn.due_date AS date,
    (('-1'::integer)::double precision * dn.value) AS value
   FROM public.due_notes dn
UNION
 SELECT rp.contract_id,
    rp.id,
    'payment'::text AS type,
    rp.date,
    rp.value
   FROM public.rent_payments_view rp
UNION
 SELECT ip.contract_id,
    ip.id,
    'payment'::text AS type,
    ip.date,
    (ip.interest + ip.amortization) AS value
   FROM public.installment_payments_view ip;


create or replace view "public"."contracts_balances_view" as  SELECT c.id AS contract_id,
    COALESCE(sum(ca.value), (0)::double precision) AS balance
   FROM (public.contracts c
     LEFT JOIN public.contracts_accounts_view ca ON ((c.id = ca.contract_id)))
  GROUP BY c.id;


create or replace view "public"."contracts_view" as  SELECT c.id,
    c.inserted_at,
    c.updated_at,
    c.type,
    c.start_date,
    c.end_date,
    c.property_id,
    c.is_active,
    cb.balance,
        CASE
            WHEN (c.type = 'lending'::public.contract_type) THEN ( SELECT to_json(lcv.*) AS to_json
               FROM public.lending_contracts_view lcv
              WHERE (lcv.id = c.id))
            WHEN (c.type = 'renting'::public.contract_type) THEN ( SELECT to_json(rcv.*) AS to_json
               FROM public.renting_contracts_view rcv
              WHERE (rcv.id = c.id))
            ELSE NULL::json
        END AS data
   FROM (public.contracts c
     LEFT JOIN public.contracts_balances_view cb ON ((c.id = cb.contract_id)));


grant delete on table "public"."addresses" to "anon";

grant insert on table "public"."addresses" to "anon";

grant references on table "public"."addresses" to "anon";

grant select on table "public"."addresses" to "anon";

grant trigger on table "public"."addresses" to "anon";

grant truncate on table "public"."addresses" to "anon";

grant update on table "public"."addresses" to "anon";

grant delete on table "public"."addresses" to "authenticated";

grant insert on table "public"."addresses" to "authenticated";

grant references on table "public"."addresses" to "authenticated";

grant select on table "public"."addresses" to "authenticated";

grant trigger on table "public"."addresses" to "authenticated";

grant truncate on table "public"."addresses" to "authenticated";

grant update on table "public"."addresses" to "authenticated";

grant delete on table "public"."addresses" to "service_role";

grant insert on table "public"."addresses" to "service_role";

grant references on table "public"."addresses" to "service_role";

grant select on table "public"."addresses" to "service_role";

grant trigger on table "public"."addresses" to "service_role";

grant truncate on table "public"."addresses" to "service_role";

grant update on table "public"."addresses" to "service_role";

grant delete on table "public"."contracts" to "anon";

grant insert on table "public"."contracts" to "anon";

grant references on table "public"."contracts" to "anon";

grant select on table "public"."contracts" to "anon";

grant trigger on table "public"."contracts" to "anon";

grant truncate on table "public"."contracts" to "anon";

grant update on table "public"."contracts" to "anon";

grant delete on table "public"."contracts" to "authenticated";

grant insert on table "public"."contracts" to "authenticated";

grant references on table "public"."contracts" to "authenticated";

grant select on table "public"."contracts" to "authenticated";

grant trigger on table "public"."contracts" to "authenticated";

grant truncate on table "public"."contracts" to "authenticated";

grant update on table "public"."contracts" to "authenticated";

grant delete on table "public"."contracts" to "service_role";

grant insert on table "public"."contracts" to "service_role";

grant references on table "public"."contracts" to "service_role";

grant select on table "public"."contracts" to "service_role";

grant trigger on table "public"."contracts" to "service_role";

grant truncate on table "public"."contracts" to "service_role";

grant update on table "public"."contracts" to "service_role";

grant delete on table "public"."contracts_tenants" to "anon";

grant insert on table "public"."contracts_tenants" to "anon";

grant references on table "public"."contracts_tenants" to "anon";

grant select on table "public"."contracts_tenants" to "anon";

grant trigger on table "public"."contracts_tenants" to "anon";

grant truncate on table "public"."contracts_tenants" to "anon";

grant update on table "public"."contracts_tenants" to "anon";

grant delete on table "public"."contracts_tenants" to "authenticated";

grant insert on table "public"."contracts_tenants" to "authenticated";

grant references on table "public"."contracts_tenants" to "authenticated";

grant select on table "public"."contracts_tenants" to "authenticated";

grant trigger on table "public"."contracts_tenants" to "authenticated";

grant truncate on table "public"."contracts_tenants" to "authenticated";

grant update on table "public"."contracts_tenants" to "authenticated";

grant delete on table "public"."contracts_tenants" to "service_role";

grant insert on table "public"."contracts_tenants" to "service_role";

grant references on table "public"."contracts_tenants" to "service_role";

grant select on table "public"."contracts_tenants" to "service_role";

grant trigger on table "public"."contracts_tenants" to "service_role";

grant truncate on table "public"."contracts_tenants" to "service_role";

grant update on table "public"."contracts_tenants" to "service_role";

grant delete on table "public"."due_notes" to "anon";

grant insert on table "public"."due_notes" to "anon";

grant references on table "public"."due_notes" to "anon";

grant select on table "public"."due_notes" to "anon";

grant trigger on table "public"."due_notes" to "anon";

grant truncate on table "public"."due_notes" to "anon";

grant update on table "public"."due_notes" to "anon";

grant delete on table "public"."due_notes" to "authenticated";

grant insert on table "public"."due_notes" to "authenticated";

grant references on table "public"."due_notes" to "authenticated";

grant select on table "public"."due_notes" to "authenticated";

grant trigger on table "public"."due_notes" to "authenticated";

grant truncate on table "public"."due_notes" to "authenticated";

grant update on table "public"."due_notes" to "authenticated";

grant delete on table "public"."due_notes" to "service_role";

grant insert on table "public"."due_notes" to "service_role";

grant references on table "public"."due_notes" to "service_role";

grant select on table "public"."due_notes" to "service_role";

grant trigger on table "public"."due_notes" to "service_role";

grant truncate on table "public"."due_notes" to "service_role";

grant update on table "public"."due_notes" to "service_role";

grant delete on table "public"."employees" to "anon";

grant insert on table "public"."employees" to "anon";

grant references on table "public"."employees" to "anon";

grant select on table "public"."employees" to "anon";

grant trigger on table "public"."employees" to "anon";

grant truncate on table "public"."employees" to "anon";

grant update on table "public"."employees" to "anon";

grant delete on table "public"."employees" to "authenticated";

grant insert on table "public"."employees" to "authenticated";

grant references on table "public"."employees" to "authenticated";

grant select on table "public"."employees" to "authenticated";

grant trigger on table "public"."employees" to "authenticated";

grant truncate on table "public"."employees" to "authenticated";

grant update on table "public"."employees" to "authenticated";

grant delete on table "public"."employees" to "service_role";

grant insert on table "public"."employees" to "service_role";

grant references on table "public"."employees" to "service_role";

grant select on table "public"."employees" to "service_role";

grant trigger on table "public"."employees" to "service_role";

grant truncate on table "public"."employees" to "service_role";

grant update on table "public"."employees" to "service_role";

grant delete on table "public"."installment_payments" to "anon";

grant insert on table "public"."installment_payments" to "anon";

grant references on table "public"."installment_payments" to "anon";

grant select on table "public"."installment_payments" to "anon";

grant trigger on table "public"."installment_payments" to "anon";

grant truncate on table "public"."installment_payments" to "anon";

grant update on table "public"."installment_payments" to "anon";

grant delete on table "public"."installment_payments" to "authenticated";

grant insert on table "public"."installment_payments" to "authenticated";

grant references on table "public"."installment_payments" to "authenticated";

grant select on table "public"."installment_payments" to "authenticated";

grant trigger on table "public"."installment_payments" to "authenticated";

grant truncate on table "public"."installment_payments" to "authenticated";

grant update on table "public"."installment_payments" to "authenticated";

grant delete on table "public"."installment_payments" to "service_role";

grant insert on table "public"."installment_payments" to "service_role";

grant references on table "public"."installment_payments" to "service_role";

grant select on table "public"."installment_payments" to "service_role";

grant trigger on table "public"."installment_payments" to "service_role";

grant truncate on table "public"."installment_payments" to "service_role";

grant update on table "public"."installment_payments" to "service_role";

grant delete on table "public"."installment_updates" to "anon";

grant insert on table "public"."installment_updates" to "anon";

grant references on table "public"."installment_updates" to "anon";

grant select on table "public"."installment_updates" to "anon";

grant trigger on table "public"."installment_updates" to "anon";

grant truncate on table "public"."installment_updates" to "anon";

grant update on table "public"."installment_updates" to "anon";

grant delete on table "public"."installment_updates" to "authenticated";

grant insert on table "public"."installment_updates" to "authenticated";

grant references on table "public"."installment_updates" to "authenticated";

grant select on table "public"."installment_updates" to "authenticated";

grant trigger on table "public"."installment_updates" to "authenticated";

grant truncate on table "public"."installment_updates" to "authenticated";

grant update on table "public"."installment_updates" to "authenticated";

grant delete on table "public"."installment_updates" to "service_role";

grant insert on table "public"."installment_updates" to "service_role";

grant references on table "public"."installment_updates" to "service_role";

grant select on table "public"."installment_updates" to "service_role";

grant trigger on table "public"."installment_updates" to "service_role";

grant truncate on table "public"."installment_updates" to "service_role";

grant update on table "public"."installment_updates" to "service_role";

grant delete on table "public"."intervention_payments" to "anon";

grant insert on table "public"."intervention_payments" to "anon";

grant references on table "public"."intervention_payments" to "anon";

grant select on table "public"."intervention_payments" to "anon";

grant trigger on table "public"."intervention_payments" to "anon";

grant truncate on table "public"."intervention_payments" to "anon";

grant update on table "public"."intervention_payments" to "anon";

grant delete on table "public"."intervention_payments" to "authenticated";

grant insert on table "public"."intervention_payments" to "authenticated";

grant references on table "public"."intervention_payments" to "authenticated";

grant select on table "public"."intervention_payments" to "authenticated";

grant trigger on table "public"."intervention_payments" to "authenticated";

grant truncate on table "public"."intervention_payments" to "authenticated";

grant update on table "public"."intervention_payments" to "authenticated";

grant delete on table "public"."intervention_payments" to "service_role";

grant insert on table "public"."intervention_payments" to "service_role";

grant references on table "public"."intervention_payments" to "service_role";

grant select on table "public"."intervention_payments" to "service_role";

grant trigger on table "public"."intervention_payments" to "service_role";

grant truncate on table "public"."intervention_payments" to "service_role";

grant update on table "public"."intervention_payments" to "service_role";

grant delete on table "public"."interventions" to "anon";

grant insert on table "public"."interventions" to "anon";

grant references on table "public"."interventions" to "anon";

grant select on table "public"."interventions" to "anon";

grant trigger on table "public"."interventions" to "anon";

grant truncate on table "public"."interventions" to "anon";

grant update on table "public"."interventions" to "anon";

grant delete on table "public"."interventions" to "authenticated";

grant insert on table "public"."interventions" to "authenticated";

grant references on table "public"."interventions" to "authenticated";

grant select on table "public"."interventions" to "authenticated";

grant trigger on table "public"."interventions" to "authenticated";

grant truncate on table "public"."interventions" to "authenticated";

grant update on table "public"."interventions" to "authenticated";

grant delete on table "public"."interventions" to "service_role";

grant insert on table "public"."interventions" to "service_role";

grant references on table "public"."interventions" to "service_role";

grant select on table "public"."interventions" to "service_role";

grant trigger on table "public"."interventions" to "service_role";

grant truncate on table "public"."interventions" to "service_role";

grant update on table "public"."interventions" to "service_role";

grant delete on table "public"."lending_contracts" to "anon";

grant insert on table "public"."lending_contracts" to "anon";

grant references on table "public"."lending_contracts" to "anon";

grant select on table "public"."lending_contracts" to "anon";

grant trigger on table "public"."lending_contracts" to "anon";

grant truncate on table "public"."lending_contracts" to "anon";

grant update on table "public"."lending_contracts" to "anon";

grant delete on table "public"."lending_contracts" to "authenticated";

grant insert on table "public"."lending_contracts" to "authenticated";

grant references on table "public"."lending_contracts" to "authenticated";

grant select on table "public"."lending_contracts" to "authenticated";

grant trigger on table "public"."lending_contracts" to "authenticated";

grant truncate on table "public"."lending_contracts" to "authenticated";

grant update on table "public"."lending_contracts" to "authenticated";

grant delete on table "public"."lending_contracts" to "service_role";

grant insert on table "public"."lending_contracts" to "service_role";

grant references on table "public"."lending_contracts" to "service_role";

grant select on table "public"."lending_contracts" to "service_role";

grant trigger on table "public"."lending_contracts" to "service_role";

grant truncate on table "public"."lending_contracts" to "service_role";

grant update on table "public"."lending_contracts" to "service_role";

grant delete on table "public"."movements" to "anon";

grant insert on table "public"."movements" to "anon";

grant references on table "public"."movements" to "anon";

grant select on table "public"."movements" to "anon";

grant trigger on table "public"."movements" to "anon";

grant truncate on table "public"."movements" to "anon";

grant update on table "public"."movements" to "anon";

grant delete on table "public"."movements" to "authenticated";

grant insert on table "public"."movements" to "authenticated";

grant references on table "public"."movements" to "authenticated";

grant select on table "public"."movements" to "authenticated";

grant trigger on table "public"."movements" to "authenticated";

grant truncate on table "public"."movements" to "authenticated";

grant update on table "public"."movements" to "authenticated";

grant delete on table "public"."movements" to "service_role";

grant insert on table "public"."movements" to "service_role";

grant references on table "public"."movements" to "service_role";

grant select on table "public"."movements" to "service_role";

grant trigger on table "public"."movements" to "service_role";

grant truncate on table "public"."movements" to "service_role";

grant update on table "public"."movements" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."properties" to "anon";

grant insert on table "public"."properties" to "anon";

grant references on table "public"."properties" to "anon";

grant select on table "public"."properties" to "anon";

grant trigger on table "public"."properties" to "anon";

grant truncate on table "public"."properties" to "anon";

grant update on table "public"."properties" to "anon";

grant delete on table "public"."properties" to "authenticated";

grant insert on table "public"."properties" to "authenticated";

grant references on table "public"."properties" to "authenticated";

grant select on table "public"."properties" to "authenticated";

grant trigger on table "public"."properties" to "authenticated";

grant truncate on table "public"."properties" to "authenticated";

grant update on table "public"."properties" to "authenticated";

grant delete on table "public"."properties" to "service_role";

grant insert on table "public"."properties" to "service_role";

grant references on table "public"."properties" to "service_role";

grant select on table "public"."properties" to "service_role";

grant trigger on table "public"."properties" to "service_role";

grant truncate on table "public"."properties" to "service_role";

grant update on table "public"."properties" to "service_role";

grant delete on table "public"."rent_payments" to "anon";

grant insert on table "public"."rent_payments" to "anon";

grant references on table "public"."rent_payments" to "anon";

grant select on table "public"."rent_payments" to "anon";

grant trigger on table "public"."rent_payments" to "anon";

grant truncate on table "public"."rent_payments" to "anon";

grant update on table "public"."rent_payments" to "anon";

grant delete on table "public"."rent_payments" to "authenticated";

grant insert on table "public"."rent_payments" to "authenticated";

grant references on table "public"."rent_payments" to "authenticated";

grant select on table "public"."rent_payments" to "authenticated";

grant trigger on table "public"."rent_payments" to "authenticated";

grant truncate on table "public"."rent_payments" to "authenticated";

grant update on table "public"."rent_payments" to "authenticated";

grant delete on table "public"."rent_payments" to "service_role";

grant insert on table "public"."rent_payments" to "service_role";

grant references on table "public"."rent_payments" to "service_role";

grant select on table "public"."rent_payments" to "service_role";

grant trigger on table "public"."rent_payments" to "service_role";

grant truncate on table "public"."rent_payments" to "service_role";

grant update on table "public"."rent_payments" to "service_role";

grant delete on table "public"."rent_updates" to "anon";

grant insert on table "public"."rent_updates" to "anon";

grant references on table "public"."rent_updates" to "anon";

grant select on table "public"."rent_updates" to "anon";

grant trigger on table "public"."rent_updates" to "anon";

grant truncate on table "public"."rent_updates" to "anon";

grant update on table "public"."rent_updates" to "anon";

grant delete on table "public"."rent_updates" to "authenticated";

grant insert on table "public"."rent_updates" to "authenticated";

grant references on table "public"."rent_updates" to "authenticated";

grant select on table "public"."rent_updates" to "authenticated";

grant trigger on table "public"."rent_updates" to "authenticated";

grant truncate on table "public"."rent_updates" to "authenticated";

grant update on table "public"."rent_updates" to "authenticated";

grant delete on table "public"."rent_updates" to "service_role";

grant insert on table "public"."rent_updates" to "service_role";

grant references on table "public"."rent_updates" to "service_role";

grant select on table "public"."rent_updates" to "service_role";

grant trigger on table "public"."rent_updates" to "service_role";

grant truncate on table "public"."rent_updates" to "service_role";

grant update on table "public"."rent_updates" to "service_role";

grant delete on table "public"."renting_contracts" to "anon";

grant insert on table "public"."renting_contracts" to "anon";

grant references on table "public"."renting_contracts" to "anon";

grant select on table "public"."renting_contracts" to "anon";

grant trigger on table "public"."renting_contracts" to "anon";

grant truncate on table "public"."renting_contracts" to "anon";

grant update on table "public"."renting_contracts" to "anon";

grant delete on table "public"."renting_contracts" to "authenticated";

grant insert on table "public"."renting_contracts" to "authenticated";

grant references on table "public"."renting_contracts" to "authenticated";

grant select on table "public"."renting_contracts" to "authenticated";

grant trigger on table "public"."renting_contracts" to "authenticated";

grant truncate on table "public"."renting_contracts" to "authenticated";

grant update on table "public"."renting_contracts" to "authenticated";

grant delete on table "public"."renting_contracts" to "service_role";

grant insert on table "public"."renting_contracts" to "service_role";

grant references on table "public"."renting_contracts" to "service_role";

grant select on table "public"."renting_contracts" to "service_role";

grant trigger on table "public"."renting_contracts" to "service_role";

grant truncate on table "public"."renting_contracts" to "service_role";

grant update on table "public"."renting_contracts" to "service_role";

grant delete on table "public"."tenants" to "anon";

grant insert on table "public"."tenants" to "anon";

grant references on table "public"."tenants" to "anon";

grant select on table "public"."tenants" to "anon";

grant trigger on table "public"."tenants" to "anon";

grant truncate on table "public"."tenants" to "anon";

grant update on table "public"."tenants" to "anon";

grant delete on table "public"."tenants" to "authenticated";

grant insert on table "public"."tenants" to "authenticated";

grant references on table "public"."tenants" to "authenticated";

grant select on table "public"."tenants" to "authenticated";

grant trigger on table "public"."tenants" to "authenticated";

grant truncate on table "public"."tenants" to "authenticated";

grant update on table "public"."tenants" to "authenticated";

grant delete on table "public"."tenants" to "service_role";

grant insert on table "public"."tenants" to "service_role";

grant references on table "public"."tenants" to "service_role";

grant select on table "public"."tenants" to "service_role";

grant trigger on table "public"."tenants" to "service_role";

grant truncate on table "public"."tenants" to "service_role";

grant update on table "public"."tenants" to "service_role";

grant delete on table "public"."tickets" to "anon";

grant insert on table "public"."tickets" to "anon";

grant references on table "public"."tickets" to "anon";

grant select on table "public"."tickets" to "anon";

grant trigger on table "public"."tickets" to "anon";

grant truncate on table "public"."tickets" to "anon";

grant update on table "public"."tickets" to "anon";

grant delete on table "public"."tickets" to "authenticated";

grant insert on table "public"."tickets" to "authenticated";

grant references on table "public"."tickets" to "authenticated";

grant select on table "public"."tickets" to "authenticated";

grant trigger on table "public"."tickets" to "authenticated";

grant truncate on table "public"."tickets" to "authenticated";

grant update on table "public"."tickets" to "authenticated";

grant delete on table "public"."tickets" to "service_role";

grant insert on table "public"."tickets" to "service_role";

grant references on table "public"."tickets" to "service_role";

grant select on table "public"."tickets" to "service_role";

grant trigger on table "public"."tickets" to "service_role";

grant truncate on table "public"."tickets" to "service_role";

grant update on table "public"."tickets" to "service_role";

grant delete on table "public"."vendors" to "anon";

grant insert on table "public"."vendors" to "anon";

grant references on table "public"."vendors" to "anon";

grant select on table "public"."vendors" to "anon";

grant trigger on table "public"."vendors" to "anon";

grant truncate on table "public"."vendors" to "anon";

grant update on table "public"."vendors" to "anon";

grant delete on table "public"."vendors" to "authenticated";

grant insert on table "public"."vendors" to "authenticated";

grant references on table "public"."vendors" to "authenticated";

grant select on table "public"."vendors" to "authenticated";

grant trigger on table "public"."vendors" to "authenticated";

grant truncate on table "public"."vendors" to "authenticated";

grant update on table "public"."vendors" to "authenticated";

grant delete on table "public"."vendors" to "service_role";

grant insert on table "public"."vendors" to "service_role";

grant references on table "public"."vendors" to "service_role";

grant select on table "public"."vendors" to "service_role";

grant trigger on table "public"."vendors" to "service_role";

grant truncate on table "public"."vendors" to "service_role";

grant update on table "public"."vendors" to "service_role";

CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.contracts FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');

CREATE TRIGGER insert_contract INSTEAD OF INSERT ON public.contracts_view FOR EACH ROW EXECUTE FUNCTION public.insert_contract();

CREATE TRIGGER update_contract INSTEAD OF UPDATE ON public.contracts_view FOR EACH ROW EXECUTE FUNCTION public.update_contract();

CREATE TRIGGER insert_installment_payment INSTEAD OF INSERT ON public.installment_payments_view FOR EACH ROW EXECUTE FUNCTION public.insert_installment_payment();

CREATE TRIGGER remove_installment_payment INSTEAD OF DELETE ON public.installment_payments_view FOR EACH ROW EXECUTE FUNCTION public.remove_installment_payment();

CREATE TRIGGER insert_intervention_payment INSTEAD OF INSERT ON public.intervention_payments_view FOR EACH ROW EXECUTE FUNCTION public.insert_intervention_payment();

CREATE TRIGGER remove_intervention_payment INSTEAD OF DELETE ON public.intervention_payments_view FOR EACH ROW EXECUTE FUNCTION public.remove_intervention_payment();

CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.lending_contracts FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');

CREATE TRIGGER validate_property_parent BEFORE INSERT OR UPDATE ON public.properties FOR EACH ROW EXECUTE FUNCTION public.validate_property_parent();

CREATE TRIGGER insert_rent_payment INSTEAD OF INSERT ON public.rent_payments_view FOR EACH ROW EXECUTE FUNCTION public.insert_rent_payment();

CREATE TRIGGER remove_rent_payment INSTEAD OF DELETE ON public.rent_payments_view FOR EACH ROW EXECUTE FUNCTION public.remove_rent_payment();

CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.renting_contracts FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


