name: Supabase Deploy

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Push Config
        run: supabase config push

      - name: Push Migrations
        run: supabase db push

      - name: Seed Buckets
        run: supabase seed buckets --linked

      - name: Deploy Functions
        run: supabase functions deploy
